backend/lambdas/events/event_dispatch/event_dispatch/event_dispatch.py
backend/terraform/modules/secrets_management/main.tf
backend/terraform/modules/secrets_management/variables.tf

- Fix bug in event dispatch lambda when handling additional routing
- Update secrets management Terraform so the lambda can access Secrets Manager
Events were not being processed correctly
Deployed changes to test environment and verified operation.

Fixes for the event dispatch and secrets management

---

README.md
ui/README.md

Update Readme files to remove invalid information and update links
Keep Readme information up-to-date.
Readme files pass Markdownlint

Readme Updates

---

ui/.dockerignore
ui/Dockerfile.dev
ui/Makefile

`publicCustom` directory was removed but still referenced in docker files, so container builds would fail
Also echo node version in `make install` step for visibility
Bug fix so that container can build
Container now builds & runs as expected

UI: fix dockerfile build

---

ui/README.md

Update README with additional info on updating package version
Clarifies package versioning
Doc-only change

update README with additional info on updating package version

---

backend/lambdas/generators/json_report/json_report/results/secret.py

Stopgap measure so that new secret types aren't filtered out
The ghas_secrets plugin introduced a large number of new secret types. The list of types will expand as GitHub adds additional detections:
https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns
Secret filtering via the API assumes the type is one of a small number of static types. This was causing the new secrets from the ghas_secrets plugin to get filtered out of the results because they didn't match the expected types. As a workaround, this boolean is used to bypass the type filtering when no types are specified.
A better solution would be to store a list of secret types in the database and update it based on the results of plugins so that when new detections are added the list is updated …

Stopgap measure so that new secret types aren't filtered out

---

backend/engine/plugins/github_repo_health/cli/src/utilities/errors.py
backend/engine/plugins/github_repo_health/cli/src/utilities/github.py
backend/engine/plugins/github_repo_health/main.py
backend/engine/tests/test_plugin_github_repo_health.py
backend/engine/utils/plugin.py
backend/lambdas/events/event_dispatch/event_dispatch/event_dispatch.py
backend/terraform/modules/analyzer/db.tf
backend/terraform/modules/analyzer/event_stream.tf
backend/terraform/modules/analyzer/variables.tf

- Update the event dispatch lambda for routing of configuration events
- Update github_repo_health plugin to return event info
- Update the engine to process configuration event info
- Fix issue with event routing permissions
- Update DB config to latest PostgreSQL 11.x version supported by Aurora
There is a desire to send GitHub repository configuration findings to downstream systems for additional processing and/or automatic remediation.
- Unit testing
- Testing in running Artemis environment

Update event routing for configuration events

---

backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf

Updated engine AMIs from "amzn2-ami-kernel-5.10-hvm-2.0.20220426.0-x86_64-gp2" to "amzn2-ami-kernel-5.10-hvm-2.0.20230404.0-x86_64-gp2"
This reduces the number vulnerabilities in the engine
Ran scans with both old and new images deployed and compared results. There seem to be no inconsistencies.

Update AMIs for Artemis engine

---

backend/lambdas/generators/sbom_report/sbom_report/report.py

Fix misleading comment and improve log message
This comment came in after the PR was already merged: https://github.com/WarnerMedia/artemis/pull/48#pullrequestreview-1421117028
N/A

Fix misleading comment and improve log message

---

orchestrator/Makefile
orchestrator/example.mk
orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_gitlab.py
orchestrator/lambdas/layers/heimdall_orgs/setup.py
orchestrator/lambdas/layers/heimdall_repos/setup.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/aws_utils.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/github/app.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/variables.py
orchestrator/lambdas/layers/heimdall_utils/setup.py
orchestrator/lambdas/org_queue/org_queue/org_queue.py
orchestrator/lambdas/org_queue/setup.py
orchestrator/lambdas/repo_queue/setup.py
orchestrator/lambdas/repo_scan/setup.py
orchestrator/terraform/environments/example/main.tf
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/outputs.tf
orchestrator/terraform/modules/heimdall/s3.tf
orchestrator/terraform/modules/heimdall/variables.tf

These are fixes and improvements to the build and deployment process.
Unrelated to the deployment fixes but included out of necessity:
- Pin urllib3 version to 1.x because of compatibility issue with botocore: https://github.com/boto/botocore/issues/2926
Doing a fresh deployment of the orchestrator uncovered some issues that remained from the OSS port.
Fresh deployments succeed

Orchestrator fixes and improvements

---

ui/package-lock.json
ui/package.json

Updated the following library:
* axios
This change was required because the axios dependency was out of date and a newer version have been released without breaking changes
* This repository has been tested through my local development environment by using the API runner utility
* Unit tests were ran and CI pipeline did not catch any breaking changes
* Changes have been deployed to a test environment and was smoke tested

Updating Axios Library

---

backend/docker-compose.local.yml
backend/local_env.py

- LocalStack v1.3 [deprecated](https://github.com/localstack/localstack/issues/7257) the `DEFAULT_REGION` variable; this PR removes usage of that variable in `docker-compose.local.yml` in favor of the AWS-native `AWS_DEFAULT_REGION`.
- Updates local environment variable `INTERNAL_ARTEMIS_SCAN_DATA_S3_ENDPOINT` to `http://{containername}:4566` to resolve traffic routing issue when running Artemis locally
- Adds missing variable `ARTEMIS_LOCAL_SERVICES_OVERRIDE` to local environment variable setup script
Smoother onboarding when setting up local Artemis environment.
Local testing (the updated files are only used when running Artemis locally).

Bugfix: Update local environment setup files

---

docs/contributors.md

Add @faizan12123 to contributors.md
Credit where it's due
N/A

Add @faizan12123 to contributors.md

---

.github/workflows/test_backend.yml
.github/workflows/test_orchestrator.yml

Updates the version of the `setup-python` GitHub Action used for backend and orchestrator unit tests.
Currently-used version is several major versions behind. This updates to latest.
Tested by triggering the backend and orchestrator unit test workflows with the new dependency version.
- [backend workflow test](https://github.com/WarnerMedia/artemis/actions/runs/7426256844)
- [orchestrator workflow test](https://github.com/WarnerMedia/artemis/actions/runs/7426256848)

update setup-python action version

---

ui/src/api/server.ts

Upgrading **mirageJS**  in [This PR](https://github.com/WarnerMedia/artemis/pull/88) introduced an issue when compiling the UI.  
- MirageJS was updated from version 0.1.47 to 0.1.48
- [version 0.1.48 introduced new types](https://github.com/miragejs/miragejs/compare/v0.1.47...v0.1.48#diff-093ad82a25aee498b11febf1cdcb6546e4d223ffcb49ed69cc275ac27ce0ccceR44) for the  field `queryparams` Causing this UI file `ui/src/api/server.ts` to throw this error: `TS2345`
Tested in a dev enironment

Update MirageJS Fields 

---

backend/engine/plugins/owasp_dependency_check/main.py
backend/engine/tests/data/owasp_dependency_check/dependency-check-report.json
backend/engine/tests/data/owasp_dependency_check/parsed-output.json
backend/engine/tests/test_owasp_dependency_check.py
backend/engine/utils/plugin.py

**What Changed?**
__This PR:__
- Updates the docker command that builds java projects
- Updates the plugin to only run when a pom.xml file is detected in the working directory
- Adds functionality to parse errors reported in the scanner's JSON output
- Disables some of the Node and Ruby scanners that run with `dependency-check`
- Adds in unit tests for the owasp plugin
This PR fixes the build and reporting issues in the `dependency-check` plugin. Currently, the scanner is unable to build pom.xml files or generate an output due to different reasons. For example:
1. **Docker Command Issue:** This command fails to run because, there is no container image named [`plugin` in this project](https://github.com/WarnerMedia/artemis/blob/main/backend/engine/plugins/owasp_dependency_check/main.py#L30) …

Update Owasp Dependency Check Plugin

---

backend/Dockerfiles/Dockerfile.veracode

Updating packages that became outdated in veracode's dockerfile
To keep veracode's dockerfile up to date

updating dockerfile for veracode

---

backend/engine/metadata/util.py
backend/libs/artemisdb/artemisdb/artemisdb/models.py
backend/libs/artemisdb/artemisdb/artemisdb/paging.py

This PR adds important details about an error to the existing logs

Update logs for loading modules

---

backend/lambdas/api/system_services/system_services/util/const.py
backend/lambdas/api/system_services/system_services/util/service.py
backend/terraform/modules/analyzer/api_system.tf

- Updates the services endpoint to support Bitbucket Cloud API v1
- Adds the following environment variables to the services lambda. These variables are needed to create a valid HTTP request
```
ARTEMIS_REVPROXY_DOMAIN_SUBSTRING,
ARTEMIS_REVPROXY_SECRET,
ARTEMIS_REVPROXY_SECRET_REGION  
```
- Updates a broken import for `repo.utils.aws`. This import is not allowed because this module is not a shared layer
The `/users/` endpoint is not available in the rest api for Bitbucket Cloud v1
Tested locally and in a dev environment

Update the Service API to support Bitbucket Cloud API v1

---

orchestrator/Pipfile
orchestrator/Pipfile.lock

This PR updates the cryptography python package

Update Artemis Packages

---

backend/engine/utils/git.py

This PR Updates the repo URLs passed to `git config`. This allows git to pickup the right http header when `git clone` is run  
Tested in a dev environment

Update Git Config URL

---

.github/workflows/test_backend.yml
.github/workflows/test_orchestrator.yml
.github/workflows/test_ui.yml

Updating actions/checkout from version 4.1.1 to 4.1.2
Keeping GitHub actions updated
Tested in dev environment

bumping actions/checkout to newer version

---

backend/Dockerfiles/Dockerfile.python3
backend/Makefile

Specified the version for the packaging library for the Checkov Plugin

Specify Checkov Package

---

backend/Dockerfiles/data/secret-patterns
backend/engine/plugins/gitsecrets/secrets_processor.py

Update git-secrets to support GitHub fine-grained personal access tokens

Add support for Github Fine-Grained Personal access tokens

---

ui/src/pages/UsersPage.tsx

Simplifies the regex used to validate scopes assigned for a new user. Removed unneeded token quantifiers.
Simplifies regex validation of entered values.
This has been tested in a non-production environment.

Simplify regex used to validate new user scopes

---

backend/Dockerfiles/Dockerfile.node14
backend/engine/plugins/eslint/eslintrc.js
backend/engine/plugins/eslint/main.py

This PR:
-  Updates the default config for Eslint to support typescript and the latest version of ECMAScript
- Configures the security library to load the [right plugin](https://github.com/eslint-community/eslint-plugin-security?tab=readme-ov-file#usage) 
- Adds a version for ESLINT because v9.0.0 [will break the existing configuration](https://eslint.org/docs/latest/use/configure/configuration-files)
and v9.0.0 will not support Node versions below v19 - https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/#flat-config-now-the-default-and-has-some-changes

Eslint update

---

backend/lambdas/api/repo/repo/github_util/github_utils.py

This reverts commit 194122813538a20317d9c6be918bce1b42220b7b.
Reverting PRs that are breaking Artemis
This [PR](https://github.com/WarnerMedia/artemis/pull/111) is breaking artemis. Just reverting to fix it temporarily

Revert Breaking PRs

---

backend/engine/plugins/lib/trivy_common/parsing_util.py
backend/engine/plugins/trivy/main.py
backend/engine/plugins/trivy_sca/main.py
backend/engine/tests/test_trivy_sca.py

When trivy had no results, a type error would occur from expecting results as a key from the returned json
fix trivy bug
built and ran locally and in a dev environment

trivy bug fix

---

backend/Pipfile
backend/Pipfile.lock

SQLparse was outdated
To keep packages updated
Tested in a dev environment

updating outdated package

---

backend/engine/processor/processor.py

Add the service to the metadata splunk events payload
tested in nonprod

Add service field to metadata events

---

backend/engine/processor/processor.py

Add service to the metadata splunk event

Metadata event update

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/gitlab_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/cloud_bitbucket_class.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/server_v1_bitbucket_class.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py
orchestrator/terraform/modules/heimdall/messaging.tf

This PR:
- Updates Heimdall's Bitbucket processor to query the latest commit for a timestamp
- Updates Heimdall's Gitlab processor to handle missing timestamps
- Adds a deadletter queue for the repo-queue and the org-queue
tested locally and in a dev environment

Heimdall Bug fix

---

.github/workflows/test_backend.yml
.github/workflows/test_orchestrator.yml
.gitignore
backend/.coveragerc
backend/Makefile
backend/pytest.ini

This improves the test runners to improve speed and consistency between local dev and CI runs.  It also cleans up the coverage report to be more useful.
* Speedups:
* Remove `venv` setup target which reinstalls Pipenv every time.  Pipenv is already a requirement to build.
* Remove "pipenv check" step.
* Bugfixes:
* Fix "make test" target failing with syntax error.
* Fix "make end2end-test" by moving `lambdas/generators/json_report` to the common `PYTHONPATH`.
* Fix `PYTEST_EXTRA_ARGS` not being passed to some targets.
* Fix locally-installed versions of tools being preferred instead of our project-specific verisons.
* Install Trivy in a project-relative directory instead of hard-coded system directory.
* Cleanups:
* Fix coverage tracking to include more source files, as well as filtering …

Backend test consistency fixes and cleanups

---

.github/workflows/test_backend.yml
backend/.test-ci

Removed the environment variables we were setting when running the backend unit tests in CI.
These environment variables may have been used in the past, but are no longer necessary.
Tested via CI.

Remove env vars for unit tests.

---

backend/lambdas/events/splunk_handler/splunk_handler/handler.py
backend/terraform/modules/analyzer/audit_log.tf
backend/terraform/modules/analyzer/variables.tf

This adds the option to hide the details (secrets) from the audit log that is sent to Splunk
Sometimes we don't want them to show up in Splunk

adding option to hide details from audit log

---

backend/lambdas/api/search_scans/search_scans/get.py
backend/lambdas/api/search_scans/search_scans/util/events.py
backend/lambdas/api/spec.yaml

Add a plugin filter to the search scan API endpoint
- [] I have added tests to cover my changes.
- [ x All new and existing tests passed.

Add plugin filter to the search scan API endpoint

---

backend/Makefile
backend/Pipfile
backend/Pipfile.lock

- `awscli` is used in the engine and needs to be installed for proper functionality.
- Changes to the `detekt` path in the Makefile were causing build issues, so reverting for now
Ensure proper engine functionality
Tested in a non-production environment.

Move awscli out of dev-dependencies, revert detekt path

---

backend/lambdas/events/splunk_handler/splunk_handler/handler.py

This PR updates the logic for removing the `details` from a splunk event. 
Right now, setting the value for `ARTEMIS_SCRUB_DETAILS` to `false` still sets the variable `SCRUB_DETAILS` to `true`
We recently added a feature to remove the `details` field from the data sent to Splunk in PR: https://github.com/WarnerMedia/artemis/pull/150

Update logic for scrubbing audit details

---

orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_private_github.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/gitlab_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py

This PR: 
- Updates the GraphQL queries to allow Null values for the cursor variable
- Sets the default cursor(`'null'`) to the python `None` type. To prevent GraphQL from reading it in as a string and not a null object

Update Orchestrator GraphQL queries 

---

backend/Pipfile
backend/Pipfile.lock
backend/libs/artemislib/artemislib/aws.py
backend/libs/artemislib/tests/test_aws_connect.py
orchestrator/Pipfile
orchestrator/Pipfile.lock

* Upgrade [Moto](https://pypi.org/project/moto/) to v5.
* Add initial unit tests (and accompanying documentation) to artemis/backend/libs/artemislib/artemislib/aws.py to verify Moto works.
[Moto](https://pypi.org/project/moto/) is a mock library for AWS services which we've included as a dependency for a while but haven't used yet.
Moto v5 also removes the python-jose dependency which has been the source of a number of CVEs in our dependency list.
Ran tests locally and in CI.  Tested in nonprod environment.

Upgrade to Moto v5

---

backend/Pipfile
backend/Pipfile.lock
orchestrator/Pipfile
orchestrator/Pipfile.lock

* python-jose removed (no longer used).
* requests added (promoted to direct dep).
This update also unsets the `allow_prereleases` option, since we no longer have any dependencies that need to be locked to prerelease versions.
Regular dependency update.

Update Python dependencies (2024-06-03)

---

.github/workflows/test_backend.yml
.github/workflows/test_orchestrator.yml
.github/workflows/test_ui.yml

Update github actions that are used in our github workflows
tested locally with https://github.com/nektos/act

Update Github Actions

---

orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_private_github.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py
orchestrator/lambdas/tests/data/github_org_error_response.json
orchestrator/lambdas/tests/data/github_repo_ref_response.json
orchestrator/lambdas/tests/data/github_repo_response.json
orchestrator/lambdas/tests/test_github_utils.py
orchestrator/lambdas/tests/test_org_queue_github.py

This PR:
- Handle GraphQL errors in private GitHub organizations
- Delete the the default branch name when processing github repos
- Update Bitbucket query for bitbucket v2
The branch field has to be `null` to trigger an Artemis scan on the default branch
tested locally and in a dev environment

Update Heimdall to queue scans for the default branch

---

backend/lambdas/events/splunk_handler/splunk_handler/handler.py

This PR Adds a check for the details field in Splunk event before deleting
The metadata event json do not have a `details` field. This raises a `KeyError` when the artemis attempts to delete the `details` key in a metadata event

Resolve Keyerror in Splunk handler

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py

This PR Reduces the amount of data returned from the [`GITHUB_REPO_QUERY`](https://github.com/WarnerMedia/artemis/pull/193/files#diff-0cd1ea69103fc479ced043550921cfbb41ecca73f3749222336413c290b85029L48-L85)
Github has a rate limit of `5000 nodes` per hour. In the worst case the `GITHUB_REPO_QUERY` would return: `5625 nodes` which exceeds that rate limit. https://docs.github.com/en/graphql/overview/rate-limits-and-node-limits-for-the-graphql-api#node-limit
Updating the GraphQL query to retrieve 1 branch per repo, reduces the total nodes returned from the `GITHUB_REPO_QUERY` to `150 nodes`

Resolve rate limit errors in Github Repo Query

---

orchestrator/README.md
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/gitlab_utils.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/aws_utils.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/github/app.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/utils.py
orchestrator/lambdas/org_queue/org_queue/org_queue.py
orchestrator/lambdas/repo_queue/repo_queue/repo_queue.py
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/variables.tf

This PR:
- Deprecates the `HEIMDALL_LOG_LEVEL` environment variable. Log levels for Heimdall Lambdas can be configured through the Application and System log variables
- Reduces noise from logs: 
- Update log levels
- add more keys to logs
- set `application_log_level` to `INFO`
- set `system_log_level` to `WARN`

Update Heimdall logs

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/aws_utils.py
orchestrator/lambdas/repo_queue/repo_queue/repo_queue.py
orchestrator/lambdas/repo_queue/repo_queue/repo_queue_env.py
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/messaging.tf
orchestrator/terraform/modules/heimdall/variables.tf

Send failed messages from the `repo-queue Lambda` to the `org-dead-letter queue`

Send Failed Messages to a DLQ (1)

---

backend/terraform/modules/analyzer/variables.tf

This should have been removed in a previous PR

cleanup var we dont need

---

orchestrator/terraform/modules/heimdall/variables.tf

update system log level for heimdall lambdas

Update log level

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py
orchestrator/lambdas/tests/test_github_utils.py
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/variables.tf

This PR:
- Removes branches from the `GITHUB_REPO_QUERY` response
- Increases the timeouts for 3rd party APIs
- Increases the memory for the `repo-queue` lambda
- Warns when GitHub tasks are unable to retrieve timestamps for branches

Requeue first Page of branches for Github tasks

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
orchestrator/terraform/modules/heimdall/messaging.tf

This pr: 
- adds the repo name to a log warning
- Removes unused iam_policy
- Updates deadletter configurations

Update redrive configurations

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py

The `repo` variable is a dictionary and not a string. This PR updates the function call to use the repo name

Update repo_name field

---

backend/Pipfile.lock

Regular update for Python dependencies.
Tests pass; also tested in a non-production environment.

Update Python dependencies (2024-07-30)

---

orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/gitlab_utils.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/artemis.py
orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/utils.py

Artemis Scans are currently stored for 180 days (6 months). This impacts Heimdall's ability to kickoff scans every 90 days (3 months) for repositories that have not changed in the past 3 months.
This PR updates Heimdall to verify that the timestamps used to query the Artemis API, is a date within 90 days from today

Trigger Batch Scans every 3 months

---

orchestrator/lambdas/org_queue/org_queue/org_queue.py
orchestrator/lambdas/repo_scan/repo_scan/repo_scan.py

1. Add new heimdall metrics:
`queued_repositories.count` and `failed_repositories.count`
2. Send the `failed_organization.count` metric on all requests processed

Update Custom Metrics

---

ui/package-lock.json
ui/src/api/server.ts
ui/src/components/SecretValidityCell.tsx
ui/src/features/hiddenFindings/hiddenFindingsSchemas.ts
ui/src/features/scans/scansSchemas.ts
ui/src/locale/en/messages.po
ui/src/pages/ResultsPage.tsx
ui/src/pages/__tests__/SecretsTabContent.test.tsx
ui/testData/testMockData.tsx

Companion to https://github.com/WarnerMedia/artemis/pull/234, exposes this new validity field in the UI
- Exposes the validity as a new column in the secrets tab findings table
- <img width="1234" alt="Screenshot 2024-08-21 at 10 22 55 AM" src="https://github.com/user-attachments/assets/72d95d22-33e3-419e-8083-cddc28b9df2c">
- With tooltips
- <img width="1244" alt="Screenshot 2024-08-21 at 10 23 08 AM" src="https://github.com/user-attachments/assets/e2e8a6e7-ea79-4842-9960-e1717f50cf91">
- Adds a filter for validity
- <img width="1242" alt="Screenshot 2024-08-21 at 10 23 25 AM" src="https://github.com/user-attachments/assets/bb566646-0321-41c4-9906-a0412d48a32a">
- <img width="1239" alt="Screenshot 2024-08-21 at 10 23 34 AM" src="https://github.com/user-attachments/assets/0de82e74-d914-49a …

Add Secret Finding Validity to UI

---

backend/terraform/modules/analyzer/api_groups.tf
backend/terraform/modules/analyzer/api_main.tf
backend/terraform/modules/analyzer/api_sbom.tf
backend/terraform/modules/analyzer/api_scans.tf
backend/terraform/modules/analyzer/api_search.tf
backend/terraform/modules/analyzer/api_system.tf
backend/terraform/modules/analyzer/db_cleanup.tf
backend/terraform/modules/analyzer/engine.tf
backend/terraform/modules/analyzer/event_stream.tf
backend/terraform/modules/analyzer/lambdas.tf
backend/terraform/modules/analyzer/license_retriever.tf
backend/terraform/modules/analyzer/messaging.tf
backend/terraform/modules/analyzer/reports.tf
backend/terraform/modules/analyzer/scan_scheduler.tf
backend/terraform/modules/analyzer/update_github_org_users.tf
backend/terraform/modules/metadata_events/main.tf
backend/terraform/modules/secrets_management/main.tf
orchestrator/terraform/modules/heimdall/lambdas.tf

Follow up from https://github.com/WarnerMedia/artemis/pull/245
This PR updates the terraform configuration for Lambdas to use the `heimdall_core` and `backend_core` Lambda layers
tested locally & in a dev environment

Update terraform configurations for Lambda Layers

---

backend/terraform/modules/analyzer/engine.tf
backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf
backend/terraform/modules/analyzer/variables.tf

Add an option to configure the engine ami

Add an option to configure the engine ami

---

backend/ci-tools/shell/artemis-scan.sh
backend/ci-tools/tests/test_artemis_scan_sh.py

artemis-scan.sh is our published script for integrating Artemis scans into CI workflows, such as GitHub Actions.
This improves our handling of cases where the REST API calls return an error, particularly non-JSON responses.
Before, these conditions would cause the script to exit immediately with a jq error message. Now we provide a proper diagnostic message to aid in debugging.
Now when printing the response body, if the body text cannot be pretty-printed as JSON, we fall back to printing the raw body. We also add default values for when extracting a JSON value fails.
We noticed failures of the script in existing CI runs but the jq errors were hiding diagnostic info.
Unit tests added. Performed a manual run against a non-prod environment.

Improve handling of API errors in artemis-scan.sh

---

backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
backend/terraform/modules/analyzer/modules/engine_cluster/permissions.tf
backend/terraform/modules/analyzer/modules/engine_cluster/templates/user_data/engine.sh
orchestrator/Makefile

Enable the datadog agent in the Artemis EC2 instances

Enable the datadog agent in the Artemis Engine

---

backend/terraform/environments/example/main.tf
backend/terraform/modules/analyzer/db_cleanup.tf
backend/terraform/modules/analyzer/lambdas.tf
backend/terraform/modules/analyzer/license_retriever.tf
backend/terraform/modules/analyzer/reports.tf
backend/terraform/modules/analyzer/scan_scheduler.tf
backend/terraform/modules/analyzer/update_github_org_users.tf
backend/terraform/modules/analyzer/variables.tf
orchestrator/terraform/modules/heimdall/lambda_networking.tf
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/s3.tf
ui/terraform/modules/analyzer-ui/s3.tf

Update the Terraform modules to be compatible with [aws `v5.66.0`](https://registry.terraform.io/providers/hashicorp/aws/latest)

Update terraform aws provider to v5.66.0

---

backend/terraform/modules/analyzer/db.tf
backend/terraform/modules/analyzer/secrets.tf

TLDR: This PR removes the [rds-aurora module](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/v2.22.0) and defines the configurations for the database resources.
Artemis uses v2.22.0 of the [`terraform-aws-rds-aurora`](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora/tree/v2.22.0) module. The latest version of this module is v9.9.1. 
Updating to the latest version of this module will require rewriting the Terraform configurations. Also, version 2.22.0 restricts our ability to make specific updates to the Terraform configurations for AWS Aurora.
To avoid future blockers, this PR removes this module and defines the AWS resources needed for Artemis

Remove the rds-aurora terraform module

---

backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/gem.py
backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/npm.py
backend/terraform/modules/analyzer/audit_log.tf
backend/terraform/modules/analyzer/event_stream.tf
backend/terraform/modules/analyzer/lambdas.tf
backend/terraform/modules/analyzer/license_retriever.tf
backend/terraform/modules/analyzer/messaging.tf
backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
backend/terraform/modules/analyzer/scan_scheduler.tf
backend/terraform/modules/metadata_events/main.tf
backend/terraform/modules/s3/main.tf
backend/terraform/modules/secrets_management/main.tf
orchestrator/terraform/modules/heimdall/lambdas.tf
orchestrator/terraform/modules/heimdall/s3.tf

1. Increase memory size for the following lambdas
- `audit-event-handler` | `128mb` ->`256mb`
- `event-dispatch` | `128mb` ->`256mb`
- `license-retriever-lambda` | `128mb` ->`512mb`
- `signin-handler` | `128mb` ->`256mb`
- `sqs-metrics` | `128mb` ->`256mb`
- `scale-down` | `128mb` ->`512mb`
- `scan-scheduler` | `128mb` ->`256mb`
- `secrets-handler` | `128mb` ->`256mb`
- `metadata-events-handler` | `128mb` ->`256mb`
- `heimdall-repo-scan` | `128mb` ->`256mb`
- `heimdall-repo-scan-loop` | `128mb` ->`256mb`
2. Update permissions for lambda roles 
3. Update deprecated aws s3 configurations 
4. Handle edge cases when retrieving licenses

Update Lamba & s3 configurations

---

backend/terraform/modules/analyzer/audit_log.tf
backend/terraform/modules/analyzer/callback.tf
backend/terraform/modules/analyzer/db_cleanup.tf
backend/terraform/modules/analyzer/event_stream.tf
backend/terraform/modules/analyzer/license_retriever.tf
backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
backend/terraform/modules/analyzer/reports.tf
backend/terraform/modules/analyzer/scan_scheduler.tf
backend/terraform/modules/analyzer/update_github_org_users.tf
backend/terraform/modules/metadata_events/main.tf
backend/terraform/modules/secrets_management/main.tf

Update the values of `DD_SERVICE` to map to the [`artemis lambda folders`](https://github.com/WarnerMedia/artemis/tree/main/backend/lambdas) 

Update Service names to match their folders

---

backend/Dockerfiles/data/secret-patterns

Fixes gitsecrets patterns
- Removes escape slash for forward slashes (there's a warning in the git-secrets output otherwise. Small thing)
- Adds double brackets around standalone `[:space:]`. `[:space:]` is equivalent to `\s` when it's already in a set, but needs double brackets (`[[:space:]]`) when it is not in a set.
- https://github.com/WarnerMedia/artemis/pull/288 had a bug, this fixes that
- Working in dev
- Bug wasn't discovered in dev before due to the `dist/docker/python3` make target not rebuilding when the secret patterns change. I've manually triggered a rebuild and it works

Fix GitSecrets Patterns

---

backend/Dockerfiles/Dockerfile.engine

Cleans up lint and format warnings in `Dockerfile.engine`.  Additionally, temporary files and cache directories are also now cleaned up, reducing the size of the image by 115 MB (814 MB before, 699 MB after).
Diff between the two images:
```diff
--- sorted-files-orig.txt	2024-09-30 15:32:08.208238775 -0400
+++ sorted-files-new.txt	2024-09-30 15:32:16.008891984 -0400
@@ -1,7 +1,5 @@
/
/.dockerenv
-/Pipfile
-/Pipfile.lock
/bin
/bin/bash
/bin/cat
@@ -774,950 +772,6 @@
/root
/root/.bashrc
/root/.cache
-/root/.cache/pip
-/root/.cache/pip/http
-/root/.cache/pip/http/0
-/root/.cache/pip/http/0/4
-/root/.cache/pip/http/0/4/1
-/root/.cache/pip/http/0/4/1/8
-/root/.cache/pip/http/0/4/1/8/c
-/root/.cache/pip/http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8 …
```

Clean up Dockerfile.engine lint warnings and cache files

---

backend/terraform/modules/analyzer/api_groups.tf
backend/terraform/modules/analyzer/api_main.tf
backend/terraform/modules/analyzer/api_sbom.tf
backend/terraform/modules/analyzer/api_scans.tf
backend/terraform/modules/analyzer/api_search.tf
backend/terraform/modules/analyzer/api_system.tf
backend/terraform/modules/analyzer/audit_log.tf
backend/terraform/modules/analyzer/callback.tf
backend/terraform/modules/analyzer/db_cleanup.tf
backend/terraform/modules/analyzer/event_stream.tf
backend/terraform/modules/analyzer/lambdas.tf
backend/terraform/modules/analyzer/license_retriever.tf
backend/terraform/modules/analyzer/messaging.tf
backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
backend/terraform/modules/analyzer/reports.tf
backend/terraform/modules/analyzer/scan_scheduler.tf
backend/terraform/modules/analyzer/update_github_org_users.tf
backend/terraform/modules/metadata_events/main.tf
backend/terraform/modules/secrets_management/main.tf

Enable JSON logging in artemis lambdas

Enable json logs in Artemis Lambdas

---

orchestrator/lambdas/org_queue/org_queue/org_queue.py
orchestrator/lambdas/repo_scan/README.md
orchestrator/lambdas/repo_scan/repo_scan/repo_scan.py
orchestrator/lambdas/tests/test_repo_scan.py

Add Trufflehog to Heimdall Scans
- Adds Trufflehog to Heimdall Scans with `depth=1`
- Github Orgs have Github Advanced Security secrets scanning to intelligently scan for secrets
- Other VCS systems do not have an analogue to GHAS. Trufflehog can do that, so we enable it in Heimdall to get that coverage
Tests pass and working in dev environment

Add Trufflehog to Heimdall Scans

---

.github/workflows/test_backend.yml
.github/workflows/test_orchestrator.yml
.github/workflows/test_ui.yml

Changes test workflows to have them run for PRs where the workflows themselves are modified.
Currently, testing workflows are not run for PRs that modify the workflows. The simplest way to test workflow changes is to run the workflows themselves.
If the workflows run as part of this PR's checks, the change succeeded.

Run tests when workflows are updated

---

backend/utilities/plugin_runner/README.md

Fixes a couple tpyos in the README of the plugin-runner utility.
N/A
Just a documentation fix.

Fix README typos

---

ui/package-lock.json
ui/package.json

Updates UI dependencies.
Regularly-scheduled dependency update.
Tests pass and works in a non-production environment.

Update UI dependencies

---

backend/engine/plugins/node_dependencies/parse.py

Testing for non-existent keys so plugin doesn't throw errors
Tested in nonprod

checking for non existent keys

---

backend/Pipfile.lock
backend/engine/tests/test_plugin_checkov.py

Uncomments some Checkov test cases that were intended for Checkov 3
- Pointed out by Mike, https://github.com/WarnerMedia/artemis/pull/319#pullrequestreview-2386765920
- Also regenerates the backend Pipfile.lock, as it became invalid with multiple PRs and poor handling of merge conflicts (my bad)
We had intended to enable these when Checkov 3 was adopted, but I missed these cases in that PR
Tests pass

Uncomment test cases for Checkov 3

---

backend/engine/plugins/bundler_audit/main.py
backend/engine/tests/test_bundler_audit.py

* Fix error handling to handle errors other than "No such file or directory".
* Ensure that the output from bundler-audit is not colorized.
* Fix type hints and docstrings.  Added additional documentation and test cases.
Fixes numerous issues discovered while testing switching to the "boxed" runner for Ruby-oriented plugins.

Clean up bundler-audit plugin

---

backend/libs/artemislib/artemislib/metrics/base.py
backend/libs/artemislib/artemislib/metrics/factory.py
backend/libs/artemislib/artemislib/metrics/provider/datadog.py
backend/libs/artemislib/setup.py

Adds a metrics library to `artemislib` and adds a custom `metrics provider` class for `datadog`

Add a metrics library to artemislib

---

backend/terraform/modules/analyzer/service_connection_metrics.tf

Update the cloudwatch permissions for the service-connections lambda

Update the cloudwatch permissions for the service-connections lambda

---

backend/engine/plugins/base_images/main.py
backend/engine/tests/test_base_images.py

Cleans up the type hints in the `base_images` plugin.
Also we add logging of a "shouldn't happen" situation, in anticipation of future updates to the regex.
Minor typing cleanups discovered while other testing.

Base Images plugin cleanup

---

backend/engine/plugins/cicd_tools/detectors/electron_forge_detector.py

- Adds `forge.config.cjs` as a possible electron forge config
- `forge.config.cjs` is an additional convention for Electron Forge configs that we do not cover

CICD Tools - Add additional Electron Forge config convention

---

backend/engine/plugins/node_dependencies/main.py

handling parse error

---

backend/engine/plugins/cicd_tools/main.py

Modifies the Azure Pipelines pattern to accept `azure-pipelines.yml` (no leading dot) and `.azure-pipelines-prod.yml` (has a suffix)
As Azure Pipelines allows the config file to be any path, we open up the pattern to match more things. 

CICD Tools - Modify Azure Pipelines pattern

---

backend/Pipfile
backend/Pipfile.lock
backend/lambdas/api/users/tests/test_put.py
backend/lambdas/api/users/tests/test_users_get.py
backend/libs/artemisdb/artemisdb/artemisdb/__init__.py
backend/libs/artemisdb/artemisdb/artemisdb/migrations/0018_refactor_cacheitem_add_fields.py
backend/libs/artemisdb/artemisdb/settings.py
backend/libs/artemisdb/setup.py

Upgrades Django to 4.2
- Django 3.2 is EOL
- We're moving to Django 4.2 LTS
- Django 4.2 LTS is supported until April 2026.
- Django v5 drops support for Python 3.9 and 5.2 LTS is not slated for release until April 2025 anyway
Moving to supported Django version

Upgrade Django to 4.2

---

backend/lambdas/api/search_repositories/search_repositories/get.py
backend/libs/artemisapi/artemisapi/const.py
backend/libs/artemisdb/artemisdb/artemisdb/models.py
backend/libs/artemisdb/artemisdb/artemisdb/paging.py

Adds a "cicd_tool" filter to the repository search endpoint
- Adds a "cicd_tool" filter to the repository search endpoint
- This is only in the API for now. We may have to follow up with further changes if this proves not performant enough
- We have CICD Tool data and would like to search for it

Add "cicd_tool" filter to repository search

---

ui/src/api/server.ts
ui/src/app/scanPlugins.ts
ui/src/features/scans/scansSchemas.ts
ui/src/features/search/searchSchemas.ts
ui/src/locale/en/messages.po
ui/src/pages/ResultsPage.tsx
ui/src/pages/SearchPage.tsx

Adds CICD Tools Plugin to UI
NOTE: Will not merge until the new year
Changes in 3 places:
- Added as option to "Inventory" dropdown
- Added as result in "Inventory" tab of Results page
- Added as a filter option on Repository tab of Search page
- Creates a new dropdown component
- Only "exact" matches work with key lookups and the exact matches would have to be with an un-intuitive ID we define. Because of this, a dropdown leads to the best user experience
- These features have been enabled API side for a bit, but we haven't exposed them as of yet
- Tests pass

Add CICD Tools Plugin to UI

---

backend/terraform/modules/analyzer/api_main.tf
backend/terraform/modules/analyzer/variables.tf
ui/terraform/modules/analyzer-ui/cloudfront.tf
ui/terraform/modules/analyzer-ui/variables.tf

This PR:
- Add an option to configure the response header policy in CloudFront 
- Add an option to configure the response headers in a custom API gateway response

Update API configurations

---

backend/lambdas/api/repo/tests/test_utils.py
backend/libs/artemisapi/artemisapi/response.py

Add security headers to API responses

Add security headers to api responses

---

backend/terraform/environments/example/main.tf
backend/terraform/modules/analyzer/lambdas.tf
backend/terraform/modules/analyzer/variables.tf

Adding option to pass env vars to repo handler lambda
Adding missing fields to example tf
Tested in nonprod

Adding repo handler vars

---

backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf

The EBS volume that I am updating is in charge of running our artemis engine. 
EBS volume was hitting thresholds of 70% usage and even ran out of storage when we tried to save too long of an NPM error

Adding more storage to EBS volume

---

backend/terraform/modules/analyzer/messaging.tf
backend/terraform/modules/analyzer/variables.tf

Add a flag for the task-queue-metrics Lambda

Add a flag for the task-queue-metrics Lambda

---

backend/Pipfile.lock
orchestrator/Pipfile.lock

Backend dependency updates.
Tested in a non-production environment.

Update backend dependencies (2025-03-12)

---

backend/Dockerfiles/Dockerfile.php

Remove obsolete `Archive_Tar` upgrade in Dockerfile.php
No longer needed as the base image in use ships with a newer version of this package
Tested in a non-production environment.

remove obsolete line in Dockerfile.php

---

backend/engine/plugins/swiftlint/main.py
backend/engine/tests/test_plugin_swiftlint.py
ui/src/pages/ResultsPage.tsx

The line numbers for Swiftlint findings are stored as strings and not integers. This PR fixes that issue

Resolve bug in swiftlint

---

ui/src/app/services.ts
ui/src/locale/en/messages.po
ui/src/utils/__tests__/formatters.test.ts
ui/src/utils/formatters.ts

Fix link handling for secrets in commit messages
- Fixes link handling for secrets in commit messages
- Factors the `vcsHotLink` url generation logic into a helper method
- Adds `commit_message` to `formatLocationName` and sorts the cases alphabetically
- Modifies `vcsHotLink` tests to not rely on the previous test runs. It seemed easier to modify the tests to be independent from each other than to worry about how to reset state with each new test.
- Commit message findings were not being handled properly in the UI
- Tests pass and working in dev environment

Fix hotlink for secrets in commit messages

---

backend/docker-bake.hcl

Set the docker platform for java builds
tested locally with docker

Set docker platform for java builds

---

orchestrator/Pipfile
orchestrator/Pipfile.lock

Update Orchestrator Dependencies (2025-03-31) 

---

backend/engine/plugins/github_repo_health/lib/src/github_repo_health/rules/first_order_rules/branch_ruleset_bypass_actors.py

Handles the case where `bypass_actors` is not provided
- This manifested itself with org rulesets, though it's unclear if it can also happen with repo rulesets. Regardless, `bypass_actors` can be None, so we should provide a default value that will behave as expected (return True)
- Fixes a bug

GRHC - Handle case where `bypass_actors` is not provided

---

backend/lambdas/scans/task_queue_metrics/task_queue_metrics/handlers.py

Error checking - avoid division by zero.
This should help avoid unhandled errors.
This change does assume that if there are zero engines in the autoscaling group, the resulting metrics are unneeded.
Tested in a non-production environment.

Avoid division by zero

---

backend/engine/processor/processor.py
backend/engine/utils/plugin.py

Update the splunk payload to include the Archive Status and the Last Commit date for a repository.

Add metadata for the Archive Status and the Last Commit date for a Repo

---

backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf

added 15 more gb to the storage of the EBS volume for cloned repos
not enough storage
in a dev environment

Add more storage to cloned_repos EBS volume

---

backend/engine/plugins/README.md
backend/engine/plugins/aqua_cli_scanner/settings.json
backend/engine/plugins/checkov/settings.json
backend/engine/plugins/owasp_dependency_check/settings.json
backend/engine/plugins/snyk/settings.json
backend/engine/plugins/trivy/settings.json
backend/engine/plugins/trivy_sbom/settings.json
backend/engine/utils/plugin.py

Not all plugins need this access
Tested in nonprod

Limiting plugin access to docker

---

backend/Dockerfiles/Dockerfile.node

Cleaning up old packages after we're done with them

adding python cleanup to node dockerfile

---

orchestrator/lambdas/repo_scan/repo_scan/repo_scan.py
orchestrator/terraform/modules/heimdall/lambdas.tf

This PR 
- Updates the `repo-scan` Lambda to handle 401(Unauthrized) error codes 
- Adds the ARTEMIS_API_KEY to the `org-queue` and `repo-queue` lambdas

Update Heimdall to handle 401 error codes from the Artemis API 

---

backend/engine/plugins/node_dependencies/parse.py

If URL is missing, generate an ID to use
Tested locally

fixing parse error

---

ui/package-lock.json
ui/package.json

Minor dependency updates to resolve dependency security issues.
Resolves findings:
* CVE-2025-7783 - form-data uses unsafe random function in form-data for choosing boundary
* CVE-2025-7339 - on-headers is vulnerable to http response header manipulation
Tested Redocly lint.
Tested UI in non-prod environment.

Security updates for form-data and on-headers

---

backend/engine/plugins/bandit/main.py
backend/engine/plugins/bandit/settings.json
backend/engine/tests/test_plugin_bandit.py

Improve error checking in bandit plugin

---

ui/.prettierignore
ui/testData/testMockData.tsx

Adds the `ui/testData` directory for formatting with Prettier.
Consistent formatting with other JS/TS files.
Ran formatter and confirmed with unit tests.

Include testData in Prettier formatting

---

backend/Dockerfiles/Dockerfile.python3
backend/Makefile

Don't just install the latest version every time

pinning bandit version

---

backend/utilities/api_runner/api_runner/main.py
backend/utilities/plugin_comparer/plugin_comparer/main.py
backend/utilities/sbom_dependency_migration/sbom_dependency_migration/main.py

These scripts are throwing errors when run because the version is stored in toml now. Fixing.
Tested locally.

using the right version

---

backend/engine/plugins/github_repo_health/lib/src/github_repo_health/utilities/checker.py
backend/engine/plugins/github_repo_health/lib/tests/test_checker.py

Fixes a regression introduced in #499 
Repo healthcheck was filtering out all config items that omitted "enabled" (when it should not have been). This fixes that
- Repo healthcheck wasn't reading configs properly

Fix repo healthcheck

---

backend/terraform/modules/analyzer/outputs.tf

Exposes `waf_acl` in the Analyzer Module
Exposes `waf_acl` in the Analyzer Module that points to the `aws_wafv2_web_acl` so that it can be used externally
- We have run into a use-case where we need to refer to the ACL. It makes more sense to directly expose it than to try to bring it in another way.
Working in dev envrionment

Expose `waf_acl` in Analyzer Module

---

backend/utilities/api_runner/api_runner/main.py
backend/utilities/plugin_comparer/plugin_comparer/main.py
backend/utilities/sbom_dependency_migration/sbom_dependency_migration/main.py

Tested locally
The other fix didn't work when running the scripts, only during build.

Fix missing versions

---

ui/src/components/ApiKeys.tsx
ui/src/locale/en/messages.po
ui/src/pages/UsersPage.tsx

The `Modify User` view in the user list was broken due to improper grid syntax. I have fixed that and upgraded those grids to grid2
This was causing the UI to not provide proper spacing between scopes in `Modify User` view
in dev environment

Fix Grid in Users Page

---

backend/lambdas/api/system_status/pyproject.toml

Fixing missing data
Tested in nonprod

adding data for package

---

ui/src/components/ApiKeys.tsx

Fixing spacing in API keys component
Tested locally and in nonprod

fixing spacing

---

backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/npm.py
backend/lambdas/maintenance/license_retriever/tests/test_retriever_npm.py

Fixing issue with how we are handling requests to the npm license retriever that was causing connection drops. Essentially just modifying the retry logic
lambda would error out

configuring retry logic for npm scanner

---

backend/Pipfile.lock

Not sure what happened, fixing lockfile

updating again

---

docs/contributors.md

Remove old account from contributors.md
