- backend/terraform/modules/analyzer/engine.tf
- backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf
- backend/terraform/modules/analyzer/variables.tf
This exposes more engine configuration variables through the top-most Terraform module so they can be set by consumers of the module for different deployments.
This is needed so that different deployments can set engine scaling to different levels.
Verified the TF against a test deployment.
> Expose more engine configuration via TF variables

- backend/terraform/modules/analyzer/secrets.tf
Fix random DB password generation to not generate invalid passwords. Also increase the password length to 32 characters.
The default set of special characters used by the `random_password` includes characters that cannot be used as PostgreSQL passwords (specifically `@`). When this occurs the Terraform errors out with:
```
module.analyzer.null_resource.aurora_db_master_password (local-exec): An error occurred (InvalidParameterValue) when calling the ModifyDBCluster operation: The parameter MasterUserPassword is not a valid password. Only printable ASCII characters besides '/', '@', '"', ' ' may be used.
```
https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password#override_special
- Verified TF applies successfully
> Fix random DB password generation to not generate invalid passwords

- backend/terraform/modules/analyzer/db.tf
- backend/terraform/modules/analyzer/engine.tf
- Add NAT engine SG to DB ingress
- Update NAT engine cluster so public=false
- Update NAT engine cluster to use Lambda routing table, which has the NAT GW route
Fixes the NAT cluster so that it does egress through the NAT gateway and can connect to the DB.
Verified against test instance that a repository that resides in a VCS requiring connectivity from a specific IP can be successfully scanned.
> Fix NAT engine cluster connectivity

- backend/terraform/modules/analyzer/engine.tf
- backend/terraform/modules/analyzer/lambdas.tf
- backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
- backend/terraform/modules/analyzer/modules/engine_cluster/templates/user_data/engine.sh
- backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf
- backend/terraform/modules/analyzer/variables.tf
This variable allows the system to determine whether to include the revproxy auth header in requests.
This change surfaces the variable configuration so that deployments can set it.
Verified against a test deployment that utilizes a reverse proxy to access a particular VCS.
> Surface configuration of ARTEMIS_REVPROXY_DOMAIN_SUBSTRING env var

- backend/Dockerfiles/Dockerfile.veracode
Update the Maven version and hash
Apache does not keep previous versions around for download so the Veracode image build was failing because it could not download the specified version.
Verified image builds
> Update the Maven version and hash

- ui/src/api/server.ts
- ui/src/components/MailToLink.test.tsx
- ui/src/components/MailToLink.tsx
- ui/src/locale/en/messages.po
Update MailToLink component to allow more than 1 email recipient (maximum 5)
Also include date user was deleted if this information is provided. 
Support more than 1 email recipient
Test email with multiple recipients are created in mail client
> UI: Support multiple recipients in MailToLink component

- backend/libs/artemislib/artemislib/github/api.py
Fix bug in how GitHub auth header was being set
This fixes a bug created during some refactoring of the ghas_secrets plugin during PR https://github.com/WarnerMedia/artemis/pull/23
- Verified in local testing
> Fix bug in how GitHub auth header was being set

- ui/.env.development
- ui/.env.production
- ui/.env.test
- ui/package-lock.json
- ui/package.json
- ui/src/api/client.test.ts
- ui/src/app/globals.ts
- ui/src/app/scanPlugins.ts
- ui/src/locale/en/messages.po
Add GitHub Advanced Security Secret Scanning plugin as an optional secrets scanning plugin.
So if this feature is enabled, you can have the option to run the GHAS Secrets plugin (or not).
Test that when enabled, GHAS Secrets plugin appears in scan plugin options and results.
> UI: Add GHAS Secret Scanning plugin

- backend/lambdas/generators/json_report/json_report/results/configuration.py
This fixes an issue where reports would fail to generate if the scan had configuration results and configuration allowlist items. Because the "id" key was removed in https://github.com/WarnerMedia/artemis/pull/31 it was not present to check against the allowlist items, causing an exception. This fix puts the "id" key back for the allowlist check.
This change also includes two line-length formatting fixes within a comment block.
Fixes bug introduced by https://github.com/WarnerMedia/artemis/pull/31
- Verified fixed in running Artemis instance
- Unit tests pass
> Fix bug in report generation with config results

- backend/terraform/modules/analyzer/outputs.tf
Add additional Terraform module outputs
The Lambda subnet and security group resources are added to the module outputs so that other modules may consume them and run Lambdas where they can reach the database.
Verified TF applies cleanly
> Add additional Terraform module outputs

- backend/terraform/environments/example/main.tf
- backend/terraform/modules/analyzer/api_main.tf
- ui/terraform/environments/example/main.tf
- ui/terraform/modules/analyzer-ui/cloudfront.tf
- ui/terraform/modules/analyzer-ui/variables.tf
Amazon recommends using TLSv1.2_2021 with Cloudfront distributions for greater security. However, this is only possible if we do not use the default Cloudfront certificate (the way it is now) which supports TLSv1+ and is not customizable. A custom certificate must exist in us-east-1 to be used with Cloudfront.
This PR does the following:
- Creates a new certificate in us-east-1
- Creates a custom DNS record that points to the Cloudfront distribution, since it is not possible to generate a certificate for the default *.cloudfront.net domain
https://avd.aquasec.com/misconfig/aws/cloudfront/avd-aws-0013
This has been tested in a development instance of Artemis
**This change requires a few variables to be defined in terraform. The example terraform files have been updated to reflect this.**
> Configure Cloudfront Distribution to use TLSv1.2_2021

- backend/aws_env.py
- backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
Require IMDSv2 when retrieving instance metadata.
For increased security, it is recommended that IMDSv2 be utilized when attempting to retrieve instance metadata.
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
Tested in a development environment. Terminated old containers after applying terraform, and ran a test scan successfully.
> Require IMDSv2 when retrieving instance metadata

- backend/Dockerfiles/Dockerfile.veracode
Updated the following components:
Debian Bullseye (11) -> Bookworm (12)
Ant 1.10.12 -> 1.10.13
Golang 1.16.3 -> 1.20.6
Gradle 7.0 -> 8.2.1
Maven 3.8.8 -> 3.9.3
Node 14.16.1 -> 18.17.0
OpenJDK 11.x -> 17.0.8
PHP 7.4.22 -> 8.2.8
Ruby 2.7.2 -> 3.1
govendor package removed. Depreciated in favor of go modules since 2019.
Pinned docker images to hashes, pinned apt packages to versions.
Several components have not been updated in a long time. This also fixes a bug that was present in the old version NPM that was causing certain scans to fail (see https://github.com/npm/npm/issues/15376).
Tested locally and ran a scan in a development environment.
> Update veracode dependencies

- backend/terraform/modules/analyzer/lambdas.tf
Updates the `signin-handler` lambda's timeout from 5 seconds to 10 seconds. 
This lambda is dependent on an HTTP request to an external identity service; this sometimes takes long enough to eat into the allotted 5 seconds and cause a timeout. This timeout, in turn, causes the authenticating user to experience a 502 error on what would otherwise be a successful request given more time.
Change has been tested in a live nonprod environment.
> Bugfix: Update signin-handler lambda timeout to 10 seconds

- backend/Dockerfiles/Dockerfile.python3
- backend/Dockerfiles/Dockerfile.veracode
- Veracode Dockerfile:
- Updated Veracode dependencies
- For packages sourced from package managers, pinned them to minor versions, rather than specific patches
- Pinned base images to `major.minor` versions, rather than specific SHAs, to accept patch-level updates
- Sources maven from a `https://repo.maven.apache.org`, which keeps previous versions available (unlike `https://downloads.apache.org`)
- python3 Dockerfile:
- Pinned base image to minor version `python3.11`, rather than major version `python3`
The Veracode container image was failing to build because some of its highly specific package versions were no longer available to `apt-get`, and because its specified version of Maven was no longer available at `https://downloads.apache.org`. This PR undoes some of the work from #62 in …
> Update Veracode dependencies and python3 base image

- backend/docker-compose.local.yml
- backend/localstack/initialize.sh
Updates `docker-compose.local.yml` to use localstack's [currently-supported initialization hooks](https://docs.localstack.cloud/references/init-hooks/), enabling automatic creation of localstack infrastructure for local development.
The `docker-entrypoint-initaws.d` initialization location was [removed](https://github.com/localstack/localstack/issues/8127#issuecomment-1505615761) in localstack v2, so the localstack infrastructure specified by `initialize.sh` was not being created automatically upon initialization of the localstack container.
Local testing (this file is only used when running Artemis locally).
> Bugfix: Update localstack init for localstack v2

- backend/engine/plugins/veracode_sbom/main.py
- backend/engine/processor/sbom.py
- backend/engine/tests/data/veracode/sample-sbom-results.json
- backend/engine/tests/test_veracode_sbom_parser.py
This change ensures that license IDs in SBOM reports are reported with the key `id`, rather than `license_id`. The `id` key was in the original spec (and is the format that Artemis' UI expects); however, this was unintentionally changed to `license_id` by #48.
#48 changed the way Artemis stores SBOM-generated dependency trees on the backend (from database to S3 bucket storage). It also unintentionally introduced a change to the format of SBOM results.
When SBOM reports were generated on-the-fly from the database, the textual representation of license objects was generated by [this to_dict() function](https://github.com/WarnerMedia/artemis/blob/670f823251cb2d77436db3ef52e77f0a3b56637f/backend/libs/artemisdb/artemisdb/artemisdb/models.py#L958-L959), which represented the `license_id` field …
> SBOM storage formatting fix

- backend/lambdas/api/authorizer/authorizer/handlers.py
- backend/lambdas/api/authorizer/tests/test_get_user.py
- backend/lambdas/api/users/users/delete.py
- backend/libs/artemislib/artemislib/audit/logger.py
This PR addresses a bug introduced by #78 which affected Artemis' ability to automatically update user email addresses based on predefined patterns.
Prior to #78, the logic which searches for user accounts matching potential aliases for a user's email address immediately returned the user account once it was found, breaking out of a couple of loops. The changes introduced in #78 deferred the return of the user account in this context in order to update the name of the user's self group as well. However, these changes did not add logic to break out of the nested loops while staying within the function, causing unexpected behavior.
The troubleshooting process for this bug also enabled the discovery of a couple of other bugs: 
- When a user account is deleted, the associated `UserService` …
> Bugfixes: email migration and user deletion

- backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
Removes the dependency on the obsolete hashicorp/template provider, which is not available for Apple Silicon Macs.
The "template_file" data source uses the hashicorp/template provider, which is officially deprecated and archived, with the functionality moved into the templatefile function in Terraform 0.12.
This is a problem because the final release of the template provider, 2.2.0, does not include a darwin_arm64 build, so folks on that platform will get the following error:
template v2.2.0 does not have a package available for your current platform, darwin_arm64
The official migration path is to use the [templatefile](https://developer.hashicorp.com/terraform/language/functions/templatefile) function instead.
This change only removes the dependency on the hashicorp/template provider, …
> Migrate away from obsolete template provider.

- backend/libs/artemislib/setup.py
When setting up in a clean environment, running api_runner may fail due to the "cryptography" module not being found.
This fix follows the pyjwt recommendation of specifying the dependency as a required extra:
https://pyjwt.readthedocs.io/en/latest/installation.html#cryptographic-dependencies-optional
Fixes initial set up in a clean environment and explicitly notes the dependency.
Tested before and after with a clean Python 3.9.18 virtualenv.
> Specify cryptography as required extra to pyjwt.

- backend/docker-compose.local.yml
This switches the database used for local development from PostgreSQL 11 to PostgreSQL 16, which is our upcoming new target version.
AWS RDS support for PostgreSQL 11.x ended on 2024-02-29.
Basic startup and API tests only so far.  This change is being made now to discover any potential issues over the next couple weeks.
> Use PostgreSQL 16.1 for local development.

- backend/lambdas/api/repo/repo/github_util/github_utils.py
A `branch_name` with a double quote causes the repo-handler's github utility to build an invalid graphql query
https://github.com/WarnerMedia/artemis/blob/fbf2847a27185ce4798580507404ffc162b97ee8/backend/lambdas/api/repo/repo/github_util/github_utils.py#L58-L70
This PR escapes double quotes in branch_names to avoid creating an invalid graphql query
Tested in a dev environment
> Escape double quotes in branch_name

- backend/libs/artemisdb/artemisdb/artemisdb/migrations/0050_dep_path_trigger.py
Modifies the `dependency_path_after_trg` trigger to avoid `IS DISTINCT FROM`, which is problematic when using pg_restore.
When using pg_dump and pg_restore to migrate the database (e.g. between major PostgreSQL versions), pg_restore will error out with:
```
pg_restore: error: could not execute query: ERROR:  operator does not exist: public.ltree = public.ltree
LINE 1: ...isdb_dependency" FOR EACH ROW WHEN (("new"."path" IS DISTINC...
^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
Command was: CREATE TRIGGER "dependency_path_after_trg" AFTER UPDATE ON "public"."artemisdb_dependency" FOR EACH ROW WHEN (("new"."path" IS DISTINCT FROM "old"."path")) EXECUTE PROCEDURE "public"."_update_descendants_dependency_path"();
```
This fix …
> Fix pg_restore error on dependency_path_after_trg.

- backend/terraform/modules/analyzer/db.tf
- backend/terraform/modules/analyzer/variables.tf
This makes the database parameter group family configurable, and sets a reasonable default if not specified.
Additionally, tags are now propagated to the database parameter group resources.
This fixes the case where the `db_engine_version` is set to something other than "11".
This is the last part necessary to support specifying a database engine version other than 11.
Tested by deploying with `db_engine_version` set to 16.
> Update the parameter group based on major version

- backend/engine/plugins/trivy_sbom/main.py
- backend/engine/plugins/trivy_sbom/parser.py
For our image sbom scans we have the metadata component name as org/repo, but for our application level SBOM scans we displayed the artemis container path. I fixed this bug by replacing it with org/repo as we have it on image scanning.
The resulting cycloneDX should not have artemis specific details incase it wants to be digested by other tools
Ran and built locally and tested in a dev environment
> Trivy- Replacing application component path

- backend/engine/plugins/ghas_secrets/main.py
GitHub doesn't support a check for advanced security on public repos, since they are enabled by default.
This was tested on nonprod
> remove check for advanced security for public repos

- backend/engine/metadata/metadata.py
- backend/engine/metadata/util.py
This enables unit tests to directly provide the allowed metadata schemes on a per-test basis, without relying on or modifying the global configuration.
`metadata.get_all_metadata()` now takes an optional loaded metadata schemes argument, which is in turn generated by the calling `metadata.load_schemes()` with the optional list of plugins to load.
When developing custom metadata scheme plugins, we want the unit tests to limit the schemes to only our plugin so that other plugins (which might be loaded from the global configuration) won't interfere.
Modified unit tests in a custom plugin to use this facility rather than setting environment variables (which affect all tests, not just for the plugin).
> Enable specifying the allowed metadata schemes

- backend/engine/metadata/metadata.py
This fixes an issue that was introduced in https://github.com/WarnerMedia/artemis/pull/125.  When the schemes is not specified (i.e. fallback to the default schemes loaded from global config), the function would fail with:
```
TypeError: 'NoneType' object is not subscriptable
```
Fixes scans not starting.
Tested in nonprod environment.
Note: We currently do not have good test coverage for this function.  We will add unit tests later, this PR is to fix the issue first.
> Fix subscript error when using default schemes.

- backend/engine/tests/test_metadata.py
- backend/lambdas/api/authorizer/tests/test_get_user.py
- backend/lambdas/api/groups/tests/test_groups_delete.py
- backend/lambdas/api/groups/tests/test_groups_post.py
- backend/lambdas/api/groups/tests/test_groups_put.py
- backend/lambdas/api/groups_keys/tests/test_groups_keys_delete.py
- backend/lambdas/api/groups_keys/tests/test_groups_keys_post.py
- backend/lambdas/api/groups_members/tests/test_groups_members_delete.py
- backend/lambdas/api/groups_members/tests/test_groups_members_post.py
- backend/lambdas/api/groups_members/tests/test_groups_members_put.py
- backend/lambdas/api/users/tests/test_put.py
- backend/lambdas/api/users_services/tests/test_users_services_post.py
- backend/lambdas/events/event_dispatch/tests/test_sm_process.py
* Better isolation for tests that invoke AWS services as a side-effect by patching-out AuditLogger and AWSConnect as necessary.
* Adds unit tests for the metadata module, which was previously modified to better support unit tests for external metadata plugins.
A number of unit tests are affected by global configuration (e.g. the AWS profile), which can cause tests to fail in one environment but succeed in other.
This attempts to avoid such situations by patching-out the bits that depend on global configuration, particularly AWS configuration.
This only touches the unit tests, so tested in separate local dev environments with separate configurations (setting the `AWS_PROFILE` environment variable to a fake value was particularly fruitful).
> Improve unit test coverage and isolation

- .github/workflows/test_backend.yml
- backend/Makefile
- backend/pytest.ini
Significantly speed up unit tests by splitting out the Black style checks into a separate test.
This significantly speeds up the backend unit tests:
```text
CI Before:  5m 35s
CI After:   2m 9s
```
* In local development, we assume that most folks will have the editor-of-choice run the formatter (i.e. Black) on save already.
* In CI where we can't rely on the pytest cache, running Black on all files at once is much faster than pytest-black since it can parallelize the checks -- pytest-black starts a new child process of Black for each individual file, which is very slow.
The `make test` target, being the "test everything" target, now includes running `style-test`.
Running the backend unit tests was particularly slow due to the way pytest-black works -- it spawns a new Black subprocess for …
> Split format checks into separate "style-test"

- orchestrator/Makefile
- orchestrator/lambdas/tests/data/services_integration.json
- orchestrator/lambdas/tests/test_get_services_integration.py
Work-in-progress minor fixes towards fixing the orchestrator integration tests.
* Updates the `services_integration.json` to include the "git.example.com" service which is referenced in the tests.
* Converts test_get_services_integration into a unit test.  To test the S3 integration in the future, we will use an S3 mock.
* Fixes a couple breaking issues when invoking the test via `make integration-test`.
The orchestrator integration tests have been broken for some time; this PR is a step towards fixing them overall.
Tested in local dev environment (note: integration tests still fail, but get further now).
> Orchestrator integration test fixes

- backend/engine/plugins/ghas_secrets/main.py
Github secret scanning has started to include scanning for pull requests and wiki pages. This is causing an error, so we're ignoring those.
Tested locally, error is no longer showing up.
> Only show secrets from code in Artemis

- backend/Makefile
- backend/engine/plugins/github_repo_health/cli/Makefile
- orchestrator/Makefile
Replaces most uses of `pipenv install` with the safer `pipenv sync`.
We retain the use of `pipenv install` in Dockerfile.engine since we use `--system` there, which is not supported by `pipenv sync` and it doesn't matter if the Pipfiles change during the image build.
`pipenv install` can unexpectedly update the Pipfile and Pipfile.lock files, which in most scenarios is not what we intend.  See the note from the [documentation](https://pipenv.pypa.io/en/latest/commands.html):
> It has been confusing to many users of pipenv that running install will completely relock the lock file.
> ...
> For now, to install lock file versions (without modification of the lock file) use: pipenv sync
Tested locally and via CI.
> Replace "pipenv install" with "pipenv sync"

- backend/terraform/modules/analyzer/db.tf
- backend/terraform/modules/analyzer/variables.tf
Enables each environment to specify the RDS Certificate Authority to use.
The default is set to `rds-ca-2019` to match [the version of the rds-aurora provider](https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws/2.29.0?tab=inputs) we're using.
This will allow us to progressively switch the RDS CA to the newer `rds-ca-ecc384-g1`.  The current `rds-ca-2019` root certs expire 2024-08-22 and AWS has been warning about the upcoming expiration for months now.
Tested with `terraform plan`.
> Make RDS CA configurable per-environment

- backend/lambdas/api/authorizer/README.md
- backend/lambdas/api/authorizer/tests/test_verify_token.py
* Add unit tests for the token signature verification and claims validation.
* Add README.md for the authorizer lambda.
> [!NOTE]
> The app ID and keypair for the unit tests were generated specifically for the tests and are not used anywhere else.
Preparation for making changes to the authorizer lambda (migrating from python-jose to joserfc).
Tested locally and in CI.
> Documentation and unit tests for authorizer

- backend/terraform/modules/analyzer/variables.tf
Switches the default AWS RDS CA to `rds-ca-ecc384-g1`.
The previous default, `rds-ca-2019`, expires on 2024-08-22.
Just changes the default value of the parameter, our deployments have already migrated by explicitly setting the `db_ca_cert_identifier` variable.
> Switch default RDS CA to rds-ca-ecc384-g1

- backend/terraform/modules/analyzer/modules/engine_cluster/templates/user_data/engine.sh
AWS is changing the latest stable version of docker to 25 from 20. Hardcoding to 20 until we confirm 25 won't break anything.
Tested in nonprod. Version is still the same.
> Pin docker version

- backend/Dockerfiles/Dockerfile.java
- backend/Makefile
* detekt.jar is now downloaded and installed within the Dockerfile.
* The download hash is now verified.
* Restored the embedded version in the unit test download path to account for changes in the specified tool version.
This is consistent with how we fetch dependent tools; we do not rely on the artifacts from the unit tests and vice-versa.
The long-term plan is for the unit tests to not be dependent on the Makefile at all.
Deployed and tested in nonprod environment.
> Fetch Detekt during build of the Java images

- backend/Pipfile
- backend/Pipfile.lock
- backend/engine/plugins/checkov/main.py
- backend/engine/tests/test_plugin_checkov.py
* Modifies the Checkov unit test to ignore changes to the ordering and message details of results.  For example, newer versions of Checkov change the URL in message details.
* Adds `trufflehog` as a dev dependency so we can detect potential dependency conflicts (in `Dockerfile.python3` in particular).
* Removed `gitpython` from `backend/Pipfile` since it's not a direct dependency.  Note that adding `trufflehog` downgrades the dependency (from 3.1 to 3.0) to the most recent compatible version.
* Fixes some lint warnings about type hints in the Checkov plugin.
This prepares us for the future updates of Checkov (v3.2), cfn_lint, and TruffleHog (v3).  These three tools share a number of dependencies and are planned to be updated soon.
All docker images built locally, unit test changes tested …
> Preparation for future tool dependency updates

- backend/engine/processor/processor.py
- backend/lambdas/api/authorizer/tests/test_get_user.py
- backend/lambdas/api/repo/repo/gitlab_util/process_gitlab_utils.py
- backend/pytest.ini
- orchestrator/pytest.ini
* Enables `--strict-config` and `--strict-markers` in pytest.
* Disables ignoring pytest warnings.
* Removed obsolete pytest config options.
* Defined custom markers.
* Cleaned up deprecation and syntax warnings detected by strict mode.
Strict mode detects typos in marker names and obsolete config options.
Tested locally and in CI.
> Enable strict mode for pytest

- .github/workflows/test_backend.yml
- .github/workflows/test_orchestrator.yml
- .github/workflows/test_ui.yml
- backend/Makefile
- backend/terraform/environments/example/variables.tf
- backend/terraform/modules/IAM/main.tf
- backend/terraform/modules/metadata_events/main.tf
- backend/terraform/modules/role_policy_attachment/main.tf
- backend/terraform/modules/role_policy_attachment/variables.tf
- backend/terraform/modules/vpc/variables.tf
- orchestrator/Makefile
- ui/Makefile
* Adds Terraform formatting check to style tests.
* Fixes formatting in existing Terraform files.
`terraform fmt` enforces the standard Terraform code style, but sometimes a manual merge or scripted edit will result in a mis-formatted file to slip through.  This adds a check for that.
Tested locally and in CI, before and after formatting fixes for existing files.
> Check Terraform formatting

- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/cloud_bitbucket_class.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/server_v1_bitbucket_class.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/repo_layer_env.py
- orchestrator/lambdas/tests/test_bitbucket_utils.py
This PR:
1. updates the `ProcessBitbucketRepos` library to support re-queueing branches in `Bitbucket Cloud v2`
2. Queues the default branch for scanning
1. `ProcessBitbucketRepos` only supports requeueing branches in [Bibtucket Server v1 ](https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#idm8287366304). this PR extends the library to also support [Bitbucket Cloud v2](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-refs/#api-repositories-workspace-repo-slug-refs-branches-name-get).
2. A scan on the default branch is triggered when the `branch` field is Null
tested locally and in a dev environment
> Support Requeueing branches in Bitbucket Cloud v2

- backend/Pipfile.lock
- backend/engine/plugins/github_repo_health/cli/Makefile
- backend/engine/plugins/github_repo_health/cli/Pipfile
- backend/engine/plugins/github_repo_health/cli/Pipfile.lock
- backend/engine/plugins/github_repo_health/cli/generated_requirements.txt
Dependency updates and match GHRC dependency versions with top-level backend pipfile
- Updates top-level Pipfile.lock
- Specifies particular versions in GHRC Pipfile to match those in top-level Pipfile where possible
- Updates GHRC Makefile
- The old `uninstall --all-dev` pattern for `update-requirements` was updating the Pipfile and removing dev dependencies. Instead, we blow away the pipenv and reinstall without dev dependencies
- The `build` target was a relic from when GHRC was a standalone command line tool. It's not anymore, so we don't need it (and removing it simplifies things a little)
- Keeping things consistent between top-level Pipfile and GHRC
- Tests pass
> Dependency updates; match GHRC dependency versions with top-level backend Pipfile

- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_bitbucket.py
- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_gitlab.py
- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_private_github.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/ado.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/gitlab_utils.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/cloud_bitbucket_class.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/objects/server_v1_bitbucket_class.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/artemis.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/aws_utils.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/get_services.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/github/app.py
- orchestrator/lambdas/repo_scan/repo_scan/aws_connect.py
The logs from child loggers do not have the additional keys declared in top level loggers([org_queue.py](https://github.com/WarnerMedia/artemis/blob/main/orchestrator/lambdas/org_queue/org_queue/org_queue.py#L23), [repo_queue.py](https://github.com/WarnerMedia/artemis/blob/main/orchestrator/lambdas/repo_queue/repo_queue/repo_queue.py#L18) etc...)
Adding the `service` field registers the child loggers to the right service
> Add service field to child loggers

- .github/.dependabot
This enables generating PRs by Dependabot for updates to the GitHub Actions workflows.
To keep the number of PRs low, we group all updates from common low-risk official sources into a single PR.  This makes it easier to review and merge during our biweekly dependency update cycle.
We are only focusing on GitHub Actions for now since we pin to version hashes in our workflows, which is difficult to do correctly manually.
Dependabot can generate PRs for updates. Currently, we are only doing this for security updates, and only generate them manually from the Dependabot alerts.
We aim to update our dependencies on a biweekly cadence, and GitHub Actions workflows are particularly difficult since we pin versions by hash.  Dependabot recognizes this style and generates PRs to match.
Using the …
> Enable grouped Dependabot PRs for GitHub Actions

- backend/lambdas/api/repo/repo/bitbucket_util/bitbucket_utils.py
- orchestrator/lambdas/repo_scan/repo_scan/repo_scan.py
- Resolve Lambda timeout errors in the `Artemis repo-handler`
- Catch Lambda timeout errors from the `Artemis repo-handler` and handle them in Heimdall
- Reduce the number of items submitted to the `Artemis repo API` from `100` to `20` repositories
- Skip branches that have been deleted
> Handle Lambda timeouts in the Artemis Repo API

- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/ado.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/bitbucket_utils.py
- orchestrator/lambdas/layers/heimdall_repos/heimdall_repos/github_utils.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/utils.py
- orchestrator/lambdas/repo_queue/repo_queue/repo_queue.py
Add a function to generate the default timestamp for a date exactly 3 months prior to the current date and time.
If a query does not have a timestamp in the response object, A default timestamp of "1970-01-01T00:00:00Z" is used. This PR updates the default timestamp to a date thats 3 months prior from the current date and time. And alerts when the default timestamp is used
> Update default timestamp

- backend/Dockerfiles/Dockerfile.dind
- backend/Makefile
- backend/engine/plugins/truffle_hog/settings.json
- backend/engine/plugins/trufflehog/main.py
- backend/engine/plugins/trufflehog/settings.json
- backend/engine/plugins/trufflehog_v3/main.py
- backend/engine/plugins/trufflehog_v3/settings.json
- backend/engine/tests/test_plugin_truffle_hog.py
- backend/engine/tests/test_plugin_trufflehog.py
- backend/lambdas/api/repo/repo/util/const.py
- backend/lambdas/api/repo/tests/test_parse_event.py
- backend/lambdas/api/spec.yaml
- ui/src/api/__tests__/client.test.ts
- ui/src/app/scanPlugins.ts
- ui/src/locale/en/messages.po
Adds a Trufflehog v3 secrets plugin
- Adds a Trufflehog v3 secrets plugin
- Splitting off from Trufflehog v2 since the v2 custom secrets patterns are not supported in the same fashion in v3 (and there are similar analogs for all of our rules within v3)
- This PR does not surface verification status of findings. That will come later
- Changes the plain english name of the old Trufflehog plugin to `Trufflehog (Legacy)`
- Trufflehog v3 is the latest version, but is meant to use its detectors rather than regular expressions. While it supports custom regular expressions, this support is described as "alpha", so we figured it'd be better to split off from v2.
- That said, many of our custom regular expressions used for v2 have similar detectors in v3. We will look at data and see if it's safe …
> Add plugin for Trufflehog v3

- backend/lambdas/api/repo/repo/util/const.py
- backend/lambdas/api/repo/tests/test_parse_event.py
- ui/src/api/__tests__/client.test.ts
- ui/src/app/scanPlugins.ts
Trufflehog v3 plugin doesn't dedupe well enough from Trufflehog v2, so this disables the plugin
- Disables trufflehog v3 plugin, since it was creating too much noise in conjunction with v2. Will re-enable once we figure out a good solution to deduping results between the two of them.
- Artemis is useful because it dedupes between many different findings. This Trufflehog v3 plugin doesn't try to consolidate between secret "types", so it causes unacceptable noise
- Tests are passing
- Working in nonprod
> Disable trufflehog v3 plugin

- backend/engine/plugins/shell_check/main.py
Fixes the invalid string escape sequences which were producing warnings.
These produced [either a DeprecationWarning or SyntaxWarning](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences), depending on the version of Python.
Detected warnings while running unit tests.
Tested locally and in CI.
> Fix invalid escape sequences in ShellCheck plugin

- backend/engine/plugins/owasp_dependency_check/main.py
- backend/engine/processor/sbom_cdx.py
- backend/engine/tests/test_trivy_sbom.py
- orchestrator/lambdas/tests/test_get_services.py
Cleans up some unused or duplicated imports.
These were detected while [migrating from Black to Ruff](https://github.com/WarnerMedia/artemis/pull/219) -- this PR cleans them up.
Tested locally and via CI.
> Clean up unused and duplicate imports

- backend/Pipfile
- backend/Pipfile.lock
- orchestrator/Pipfile
- orchestrator/Pipfile.lock
Adds [boto3-stubs](https://pypi.org/project/boto3-stubs/) to the Pipfiles.  Once installed, this will automatically provide boto3 type info in VSCode and any editor / type checker that supports type stubs.
Note that this package only provides type info, similar to TypeScript type definition modules.
Before:
After:
While researching Python type checkers, boto3's lack of type info repeatedly came up as an issue.  Adding these type stubs provides type info without changing any code and helps VSCode's autocomplete and linting (via Pylance).
Tested in VSCode.
> Add boto3-stubs for type hints

- backend/engine/plugins/gitsecrets/main.py
- backend/engine/plugins/lib/secrets_common/enums.py
- backend/engine/plugins/truffle_hog/main.py
- backend/engine/plugins/trufflehog/main.py
- backend/engine/tests/test_plugin_truffle_hog.py
- backend/engine/tests/test_plugin_trufflehog.py
- backend/lambdas/generators/json_report/json_report/results/secret.py
- backend/libs/artemisdb/artemisdb/artemisdb/consts.py
Exposes secret validity in API
- Adds "validity" field to `gitsecrets`, `trufflehog` and `truffle_hog` results
- `gitsecrets` and `truffle_hog` (legacy trufflehog) do not attempt to validate findings, so their results are always unknown
- `trufflehog` (v3) will try to validate findings and will return either Active or Unknown
- GHAS secrets already exposed the `validity` field
- Modifies the `json_report` generator to show validity
- Also fixes invalid types in files that are touched
- GHAS secrets and Trufflehog v3 can attempt to validate that findings are legitimate. We want to surface this information to users
- Tests pass
> Expose Secret Validity in API

- backend/build_scripts/update_lambda_layers.py
- orchestrator/lambdas/repo_queue/repo_queue/repo_queue.py
- orchestrator/lambdas/repo_queue/repo_queue/repo_queue_env.py
- orchestrator/terraform/modules/heimdall/lambdas.tf
This PR: 
1. Updates the `repo-queue-lambda` to send failed tasks back to SQS. This is the recommended way for handling failed tasks in Lambdas: https://docs.aws.amazon.com/lambda/latest/dg/services-sqs-errorhandling.html. 
Currently, these messages are manually sent to the Deadletter Queue 
2. Deprecates the `ORG_DEADLETTER_QUEUE` environment variable 
> Return failed Lambda messages to SQS

- backend/Makefile
- backend/Pipfile
- backend/lambdas/api/authorizer/setup.py
- backend/lambdas/api/repo/setup.py
- backend/lambdas/api/signin/setup.py
- backend/lambdas/events/metadata_handler/setup.py
- backend/lambdas/events/secrets_handler/setup.py
- backend/lambdas/events/splunk_handler/setup.py
- backend/lambdas/generators/sbom_report/setup.py
- backend/lambdas/maintenance/db_cleanup/db_cleanup/util/env.py
- backend/lambdas/maintenance/license_retriever/setup.py
- backend/lambdas/scans/callback/setup.py
- backend/lambdas/scheduled/scheduled_scan_handler/setup.py
- backend/lambdas/scheduled/update_github_org_users/setup.py
- backend/libs/artemisdb/setup.py
- backend/libs/artemislib/setup.py
- backend/utilities/plugin_comparer/setup.py
- orchestrator/Makefile
- orchestrator/Pipfile
- orchestrator/lambdas/layers/heimdall_orgs/setup.py
- orchestrator/lambdas/layers/heimdall_repos/setup.py
- orchestrator/lambdas/layers/heimdall_utils/setup.py
- orchestrator/lambdas/org_queue/setup.py
- orchestrator/lambdas/repo_queue/setup.py
- orchestrator/lambdas/repo_scan/setup.py
- orchestrator/lambdas/repo_scan_loop/setup.py
The dependencies for Artemis & Heimdall lambdas are defined in multiple locations. This setup makes it difficult to maintain consistent dependencies across all Lambdas. 
This PR updates the Makefile to generate two Lambda layers, `artemis-backend-core` and `heimdall-core` for Artemis and Heimdall Lambdas.
`artemis-core` contents:
- `artemislib`
- `artemisdb`
- `artemisapi`
- packages in `backend/Pipfile`
`heimdall-core` contents:
- `heimdall_utils`
- `heimdall_repos`
- `heimdall_orgs`
- packages in `orchestrator/Pipfile`
Moving forward, the dependencies for Heimdall or Artemis Lambdas will be managed by the Pipfiles
- For Artemis Lambdas the Lambda dependencies can be modified in [`backend/Pipfile`]()
- For Heimdall Lambdas the Lambda dependencies can be modified in [`orchestrator/Pip`]() …
> Create a single Lambda Layer for Artemis & Heimdall packages

- backend/terraform/modules/analyzer/api_groups.tf
- backend/terraform/modules/analyzer/api_main.tf
- backend/terraform/modules/analyzer/api_sbom.tf
- backend/terraform/modules/analyzer/api_scans.tf
- backend/terraform/modules/analyzer/api_search.tf
- backend/terraform/modules/analyzer/api_system.tf
- backend/terraform/modules/analyzer/audit_log.tf
- backend/terraform/modules/analyzer/callback.tf
- backend/terraform/modules/analyzer/db_cleanup.tf
- backend/terraform/modules/analyzer/engine.tf
- backend/terraform/modules/analyzer/event_stream.tf
- backend/terraform/modules/analyzer/lambdas.tf
- backend/terraform/modules/analyzer/license_retriever.tf
- backend/terraform/modules/analyzer/messaging.tf
- backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
- backend/terraform/modules/analyzer/modules/engine_cluster/variables.tf
- backend/terraform/modules/analyzer/reports.tf
- backend/terraform/modules/analyzer/scan_scheduler.tf
- backend/terraform/modules/analyzer/secrets.tf
- backend/terraform/modules/analyzer/update_github_org_users.tf
- backend/terraform/modules/analyzer/variables.tf
- backend/terraform/modules/metadata_events/main.tf
- backend/terraform/modules/metadata_events/variables.tf
- backend/terraform/modules/secrets_management/main.tf
- backend/terraform/modules/secrets_management/variables.tf
- orchestrator/terraform/modules/heimdall/lambdas.tf
Add terraform configurations to enable datadog in Artemis lambdas
> Add Datadog configurations for Artemis

- backend/Pipfile
- backend/Pipfile.lock
- backend/ci-tools/shell/artemis-scan.sh
- backend/ci-tools/tests/test_artemis_scan_sh.py
This adds unit tests for artemis-scan.sh, the script we publish for integrating Artemis scans into CI pipelines.
We mock the API calls via [pytest-httpserver](https://pytest-httpserver.readthedocs.io/en/latest/) which creates a local HTTP server for the script to call (via Curl).  This plugin was designed to be used with Pytest-style unit tests, which is why this test suite is in Pytest style rather than "classic" unittest style.
To make testing easier, artemis-scan.sh has two new scan options.  We only document these options in the source code since they're only used internally for the unit tests:
* `ARTEMIS_API` is now overridable so we can point it at the local server.
* `ARTEMIS_STATUS_INTERVAL` adjusts the time to wait between status checks of the in-progress scan, so the unit test …
> Unit tests for artemis-scan.sh

- .github/workflows/test_backend.yml
- .github/workflows/test_orchestrator.yml
setuptools v74 is causing a crash when pip installs dependencies with the error:
```
TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
```
The workaround is to constrain setuptools to v73 or earlier. We must also pin virtulenv since 20.26.4 is hard-coded to install setuptools v74 into new virtual environments.
We can likely remove this restriction when we can upgrade to packaging v24.
Resolve issues with CI build in `pipenv sync` step.
Included in other pending branches.  Splitting the fix out into a separate PR to fix other in-progress branches.
> Fix CI build by restricting setuptools to pre-v74

- backend/engine/plugins/truffle_hog/main.py
- backend/engine/plugins/trufflehog/main.py
- backend/engine/plugins/trufflehog/type_normalization.py
- backend/engine/tests/test_plugin_trufflehog.py
Normalizes Trufflehog Finding Types
- Trufflehog legacy
- Remove "other" category. Instead, returns the type from Trufflehog directly if it doesn't fall into a bin
- Trufflehog v3
- Bins finding types into the bins from Trufflehog legacy
- With the exception of urlauth, which does not have a corresponding Trufflehog v3 Detector 
- With https://github.com/WarnerMedia/artemis/pull/252 merged, `type` is not factored into de-duplication so the `other` type is just hiding useful information from the user. This PR removes that from Trufflehog Legacy
- That said, binning types is still useful in general to clean up results when a finding is found by multiple plugins, so we also add binning to the new Trufflehog plugin.
- Tests pass
> Normalize Trufflehog Finding Types

- backend/engine/plugins/gitsecrets/secret_regex.py
- backend/engine/plugins/gitsecrets/secrets_processor.py
- backend/engine/tests/test_plugin_gitsecrets.py
Add types to Gitsecrets results, instead of returning "other" for many different finding types
- Gitsecrets will now more often return a secret type, rather than binning things into an "other" bin
- We were using [old Trufflehog regexes](https://github.com/dxa4481/truffleHogRegexes/blob/9257f45e66e31ad3fefd9d6e2b2e09dfb83043d6/truffleHogRegexes/regexes.json), so this PR adds the types from those trufflehog regexes back in (except where an existing bin makes more sense)
With
https://github.com/WarnerMedia/artemis/pull/252 merged, type is not factored into de-duplication so the other type is just hiding useful information from the user. This PR removes that from gitsecrets
Working in dev environment and tests pass
> Gitsecrets Plugin - Add additional types

- backend/engine/utils/plugin.py
Type hint updates for backend/engine/utils/plugin.py before making further changes.
* Add and fix type hints.
* Reformat docstrings previously written as comments.
No changes to the code itself, only type hints and docstrings.
Separating out the simple type hint and docstring fixes from a (future) PR.
No code changes, only updates to type hints and docstrings.
> Add type hints to Engine plugin.py

- backend/engine/plugins/ghas_secrets/main.py
- backend/engine/plugins/gitsecrets/secrets_processor.py
- backend/engine/plugins/truffle_hog/main.py
- backend/engine/plugins/trufflehog/type_normalization.py
- backend/engine/tests/test_plugin_trufflehog.py
Lowercases the secret types in all secrets plugins
- Secret types with capital letters were not showing up in results, so we lowercase them all
- When writing the list of secret types, we [lowercase them all](https://github.com/WarnerMedia/artemis/blob/main/backend/engine/utils/plugin.py#L699). This creates an implicit requirement for secret types to be all lowercase, since we later [pull down this list](https://github.com/WarnerMedia/artemis/blob/main/backend/lambdas/generators/json_report/json_report/results/secret.py#L49) and [check that a given finding's type is in it](https://github.com/WarnerMedia/artemis/blob/main/backend/lambdas/generators/json_report/json_report/results/secret.py#L79)
- We also considered lowercasing in the `json_report` lambda before comparing with the list of …
> Lowercase all secrets types

- backend/engine/plugins/trivy_sbom/parser.py
- backend/engine/tests/test_trivy_sbom.py
The package names stored for trivy_sbom results are not correct. For example, packages with a group field are stored as: `@balenadockerignore` and not `@balena/dockerignore`
Adds a divider between the component group and the component name for a detected package.
Example Cyclone DX component for https://www.npmjs.com/package/@balena/dockerignore
```
{
"bom-ref": "pkg:npm/%40balena/dockerignore@1.0.2",
"type": "library",
"group": "@balena",
"name": "dockerignore",
"version": "1.0.2",
"purl": "pkg:npm/%40balena/dockerignore@1.0.2",
"properties": [
{
"name": "aquasecurity:trivy:PkgID",
"value": "@balena/dockerignore@1.0.2"
},
{
"name": "aquasecurity:trivy:PkgType",
"value": "yarn"
}
]
}
```
This affects the `artemis-license-retriever` Lambda because it uses the package name to build URLs to …
> Fix bug in trivy_sbom

- backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/go.py
- backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/pypi.py
Two tiny fixups in the license-retriever lambda that appear to be copy-paste typos:
* Remove duplicate "efl" key in PYPI_LICENSE_MAP.
* Fixed the return type of `get_package_info()` in the Go retriever.
Discovered while examining the license retriever code.
N/A -- changes don't effect the logic, just the type hint and duplicated key.
> Tiny lint cleanups in license-retriever

- backend/engine/processor/processor.py
- backend/engine/processor/scan_details.py
- backend/engine/tests/data/util/plugins/invalid/settings.json
- backend/engine/tests/data/util/plugins/minimal/settings.json
- backend/engine/tests/data/util/plugins/normal/settings.json
- backend/engine/tests/test_engine_processor.py
- backend/engine/tests/test_engine_utils.py
- backend/engine/utils/plugin.py
Applies various fixes and refactorings surrounding the `PluginSettings` type:
* Strictly validate the types when loading `settings.json` (via Pydantic).
* Field parsers for `image` and `disabled` have been moved into `PluginSettings`.
* Mark the `feature` and `timeout` fields as `Optional` since they can be `None`.
* Adds `PluginSettings.build_images` which is used in `EngineProcessor.docker_images_required()`, so we consolidate the loading of `settings.json` into one place.
* Adds test `settings.json` files so the unit tests don't depend on the actual plugins which could change.  This also fixes a longstanding xfail'd test.
* Fixes a potential `ValueError` in `ScanDetails` if the plugin directory doesn't have a `lib` directory (such as in unit tests).
Additional unit tests have been …
> Adjust PluginSettings types and add unit tests

- backend/engine/tests/data/util/plugins/invalid/settings.json
- backend/engine/tests/data/util/plugins/normal/settings.json
- backend/engine/tests/test_engine_utils.py
- backend/engine/utils/plugin.py
Adds an optional field `runner` to plugin `settings.json`.
This is a placeholder field for now to enable experimentation with different plugin runners / architectures.
We're starting on experiments on alternative methods for running plugins, so this sets the stage to select which runner each plugin will use.
Tested in nonprod environment.
> Add runner field to PluginSettings

- backend/Dockerfiles/Dockerfile.python3
- backend/Dockerfiles/data/secret-patterns
Fixes the git-secrets plugin regular expressions
- The version of grep used by git-secrets does not support `\s`, so we replace it with `[:space:]` (as per [the table here](https://www.regular-expressions.info/posixbrackets.html) that converts from shorthand to POSIX)). This should give git-secrets parity with Trufflehog, provided the full word is a match  
- `git-secrets` runs `grep -w` under the hood, which cares about words. Trufflehog does not care about words. So, with `AKIA12345678901234567` as an example (AKIA + 17 characters. A normal AWS Key ID has 16 characters), git-secrets will not find it while Trufflehog Legacy will.
- This fixes the urlauth gitsecrets rules, which drive `mongo`, `postgres`, `ftp`, `http`, and more
- Removed `--register-aws` from dockerfile, as it was …
> Fix git-secrets plugin regular expressions

- backend/pyproject.toml
- orchestrator/pyproject.toml
Adds a config section for Pyright to the `pyproject.toml` in engine and orchestrator.
Enables Pyright to be run from the command-line (i.e., instead of via an editor extension).
This will allow us to roughly gauge our progress in fixing issues over time.
```bash
pip install pyright
cd backend ; pyright
cd orchestrator ; pyright
```
> Add Pyright configuration

- backend/engine/plugins/trufflehog/main.py
Fixes an error when the finding is allowlisted
- Copy & paste error from Legacy Trufflehog. We didn't change how we access the path with the breaking change in output format between Trufflehog v2 and v3.
- Trufflehog v3 is failing when there is a finding that is also on the system allowlist
Tests pass
> Trufflehog Plugin - Fix error when finding is allowlisted

- backend/lambdas/api/repo/repo/util/const.py
- backend/lambdas/api/repo/tests/test_parse_event.py
- ui/src/api/__tests__/client.test.ts
- ui/src/app/scanPlugins.ts
Disables Legacy Trufflehog
- Git Secrets should have parity with legacy Trufflehog findings for secrets in the HEAD
- Trufflehog v3 should have coverage of git history with lower-noise detectors
- With all that in mind, we deprecate Legacy Trufflehog as it is poorly supported
- We'll remove the plugin entirely after a few days with it disabled
- Tests pass
> Disable legacy trufflehog

- backend/ci-tools/shell/artemis-scan.sh
With Legacy Trufflehog deprecated, the CI Script should exclude Trufflehog v3 rather than Legacy Trufflehog
- Excludes Trufflehog v3 rather than Legacy Trufflehog
Trufflehog by default scans commit history and that can take too long for CI, so we don't want it to run there.
> Modify CI Script to exclude Trufflehog v3

- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_bitbucket.py
- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_gitlab.py
- orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_private_github.py
- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/utils.py
- orchestrator/lambdas/org_queue/org_queue/org_queue.py
- orchestrator/lambdas/tests/test_org_queue_github.py
The main execution block in the `heimdall_org_queue` Lambda does not detect errors in the `heimdall_org` layer.
This means that some failed organizations are not caught in the main handler.
This PR updates the retrievers in the `heimdall_org` layer ([`org_queue_bitbucket`](https://github.com/WarnerMedia/artemis/blob/main/orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_bitbucket.py), [`org_queue_gitlab`](https://github.com/WarnerMedia/artemis/blob/main/orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_gitlab.py), [`org_queue_private_github`](https://github.com/WarnerMedia/artemis/blob/main/orchestrator/lambdas/layers/heimdall_orgs/heimdall_orgs/org_queue_private_github.py))  to raise a `HeimdallException` when they detect http errors
> Propagate errors in the heimdall_orgs layer

- backend/engine/plugins/trufflehog/detectors.py
- backend/engine/plugins/trufflehog/main.py
- backend/engine/tests/test_plugin_trufflehog.py
Extends the Trufflehog plugin to classify some findings as `inactive`
- The Trufflehog plugin now tries to classify as `inactive` if it can
- In the case that `verified` is False and there is no `VerificationError`
- Also checks that it's one of the detectors we try to verify (there will never be a `VerificationError` if we run with `--no-verification`)
- And that it's not one we deliberately stop from reporting as `inactive` (like the `ssh`/"PrivateKey" detector, which makes a best-effort attempt to verify with popular PrivateKey usecases, but is not exhaustive, so it can successfully check that the key isn't used with its 3 services while the key is still valid someplace else)
- Removes "Generic" detector from list of verified detectors (it doesn't do any verification, so there's no …
> Trufflehog Plugin - Classify some findings as "Inactive"

- backend/libs/artemislib/tests/test_logger.py
This fixes the `PytestDeprecationWarning` in the backend unit tests:
```
PytestDeprecationWarning: A private pytest class or function was used.
handler = LogCaptureFixture(request.node)
```
We avoid this warning by extending the built-in [caplog](https://docs.pytest.org/en/stable/reference/reference.html#pytest.logging.caplog) fixture (which essentially just creates a new LogCaptureFixture) instead of re-implementing it.
Fixes unit test warnings.
Tested via unit-tests locally and in CI.
> Fix Pytest deprecation warning about LogCaptureFixture

- backend/Pipfile.lock
- orchestrator/Pipfile
- orchestrator/Pipfile.lock
Follow-up to #329.
This updates cryptography to v43 in the dev dependencies in the lockfile, as the previous PR only updated the non-dev section.
This shouldn't actually affect anything except for clearing out the Dependabot warnings.
Resolves [GHSA-h4gh-qq45-vh27](https://github.com/advisories/GHSA-h4gh-qq45-vh27) in Dependabot.
Only affects the dependency in a dev environment, deployed environment is unchanged.
> Update cryptography to v43 in dev dependencies

- backend/utilities/plugin_runner/README.md
- backend/utilities/plugin_runner/plugin.sh
* Properly handle the case where no `.env` file exists. Before, this would cause the script to exit immediately.
* Add a new `run-writable` subcommand to support plugins that expect the target directory to be writable.
Fixes & features from feedback.
Tested locally.
> plugin-runner: Handle missing .env file and allow writable target

- backend/Pipfile
- backend/Pipfile.lock
- orchestrator/Pipfile
- orchestrator/Pipfile.lock
Adds Pyright to the dev dependencies in the Pipfiles.
> [!NOTE]
> This only adds the "pyright" command-line tool. Normally in VSCode, Pyright inherits its configuration from Pylance, so to get the same results on the command-line we will need to update `pyproject.toml` to match the settings.  That effort is still a work-in-progress, so this PR just adds Pyright to the deps for now.
Allows us to run Pyright from the command-line and ensure that we don't have any dependency conflicts.
Tested running Pyright locally, e.g.:
```
cd backend/engine
pyright .
```
> Add Pyright to dev deps

- backend/lambdas/maintenance/license_retriever/license_retriever/handlers.py
- backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/npm.py
- backend/lambdas/maintenance/license_retriever/tests/test_retriever_npm.py
- backend/pytest.ini
- Extends the NPM license retriever to cover more cases
- Can now handle SPDX license expressions
- Which is the currently-supported way to have multiple licenses: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#license
- We opted not to lose the AND/OR/WITH logic in this pull request by extracting all the mentioned license versions. SPDX expressions should be preserved as-is
- Another option is to parse the expression and return all licenses mentioned, but then we'd lose the AND/OR/WITH relationship. (We are not doing this)
- Also handles more "deprecated" license cases
- Like `license: { type: str }`
- Like `licenses: [ { type: str } ]`
There were common license patterns that we were not reading
Tests pass and working in dev environment
> Support more NPM license conventions

- backend/engine/plugins/bundler_audit/main.py
- backend/engine/tests/test_bundler_audit.py
Parsing of stdout and stderr from running bundler-audit is now more consistent, with better detection of error conditions.
A [previous fix](https://github.com/WarnerMedia/artemis/pull/323) adjusted the stderr parsing so that it no longer ignores/mangles error messages, but this exposed the issue that git (which is called by bundler-audit) writes its progress messages to stderr, which was being captured as errors.  Additionally, in one case the tool emits a fatal error message to stdout instead of stderr.
We now check the exit code of the tool as well as if any findings are present in order to determine if the errors should be reported.
A number of test cases were added based on actual test runs of bundler-audit so that the tests better reflect reality.
Fix error messages mistakenly being …
> Overhaul handling of errors from bundler-audit

- backend/Dockerfiles/Dockerfile.ruby
- backend/Makefile
- backend/engine/plugins/brakeman/settings.json
- backend/engine/plugins/bundler_audit/settings.json
Switched the Ruby plugins (Brakeman and Bundler-Audit) to use the boxed plugin runner.
Additionally, included some minor cleanups of the Dockerfile.
Simplify maintenance of `Dockerfile.ruby`.
> Switch Ruby plugins to use the boxed runner

- backend/Makefile
Removes the CI-specific logic in backend/Makefile to set `SWAGGER_CODEGEN`.
If `SWAGGER_CODEGEN` needs to be changed from the default, it should be defined via `make`, e.g.:
```bash
make dist/api/index.html SWAGGER_CODEGEN='java -jar /opt/swagger-codegen-3.0.63'
```
Simplifies the Makefile by removing unnecessary code.
Tested running `make dist/api/index.html` locally.
> Remove CI-specific logic for swagger-codegen

- backend/Dockerfiles/Dockerfile.ruby
- backend/Makefile
This upgrades the Ruby base image to use Ruby 3.3.  To support this version of Ruby, the tools have been upgraded as well:
* Brakeman upgraded to 6.2.2
* Bundler-Audit upgraded to 0.9.2
Additionally:
* Removed the separate step to upgrade security updates, which is unnecessary since we upgrade all packages anyway.
* The `linux-libc-dev` package and dependencies are removed as they are not needed in the final image, and they result in hundreds of false-positives in container scanning.
> [!NOTE]
> This is the *Debian* version of this solution.
> The Debian base image has more detected vulnerabilities than the [Chainguard version](https://github.com/WarnerMedia/artemis/pull/342), but lets us select the specific Ruby version version which should result in fewer surprises from …
> Upgrade Ruby image and tools (Debian)

- backend/engine/plugins/trivy_sbom/parser.py
Fixes a Trivy SBOM error when no version is provided
- Trivy SBOM was erroing with KeyError when no version was provided. This uses `dict.get` instead
- Uses the string "none" as the default value if it's not provided
- This is as opposed to None, since these values get thrown into a database and it's unclear what behavior passing None would lead to.
- Fixes an error
Working locally
> Fix Trivy SBOM error when no version is provided

- backend/engine/plugins/lib/utils.py
- backend/engine/plugins/trivy_sbom/main.py
- backend/engine/plugins/trivy_sbom/parser.py
Fixes an error in the Trivy SBOM plugin
- Trivy SBOM was erroring out when `output` passed to `clean_output_application_sbom` is `None`. This PR adds a check that the value is truthy to prevent this
- This PR also updates relevant types to prevent such errors in the future
- Fixes an error that occurs in Trivy SBOM
> Fix error in Trivy SBOM plugin when returned output is None

- backend/utilities/plugin_runner/README.md
Adds "Troubleshooting" and "Limitations" sections to the README of the plugin-runner tool.
Documents some things I ran into while testing the full list of plugins for https://github.com/WarnerMedia/artemis/pull/352
N/A, only updates to documentation.
> Plugin-runner: Add "Troubleshooting" and "Limitations" sections to README

- backend/engine/plugins/detekt/main.py
- backend/engine/plugins/eslint/main.py
Cleans up type hints and lint warnings found in the ESLint and Detekt plugins.
Minor cleanups collected while working on other changes.
> eslint/detekt: Clean up type hints and lint warnings

- backend/lambdas/api/spec.yaml
Migrates the API spec to OpenAPI 3.1.0.  This resolves the bulk of lint warnings from Redocly.
Preparation for switching from swagger-codegen to Redocly for documentation generation.
Passes `redocly lint` (with a config file which will be added in a follow-up PR).
> Migrate to OpenAPI 3.1.0

- ui/package-lock.json
- ui/package.json
Downgrades `@types/redux-logger` to 3.0.9.
Fixes the UI in dev mode.  Newer versions are incompatible.
Tested locally via `npm start`.
> Downgrade @types/redux-logger to 3.0.9 to fix dev mode

- backend/utilities/plugin_runner/plugin.sh
The Plugin Runner tool now supports plugins that need to use Docker (e.g. trivy).
This is accomplished the same way we do it in the AWS deployment, by mounting the `docker.sock` in the engine as a volume that gets inherited by the plugin containers -- see [`docker-compose.aws.yml`](https://github.com/WarnerMedia/artemis/blob/a2683ea51d47e07de07b6e3e3cd1a228574f070c/backend/docker-compose.aws.yml#L7).
Plugins that use Docker would previously just hang on execution.
Tested running the Trivy plugin locally.
> Plugin runner: Support plugins that use Docker

- backend/engine/plugins/lib/write_npmrc.py
Adds the option of using authToken for authenticating with .npmrc
- If an `authToken` property exists in a scope, we will use it with `_authToken` rather than the current `username` and `_password` pattern
- This is technically breaking, but it would require a scope to already include an `authToken` property despite it previously having no value.
`authToken` is preferred by some repository managers, so we should support it.
> Add "authToken" auth type for .npmrc

- backend/Dockerfiles/Dockerfile.dind
- backend/Dockerfiles/Dockerfile.python3
- backend/Makefile
- backend/engine/plugins/checkov/main.py
- backend/engine/plugins/checkov/settings.json
- backend/engine/tests/test_plugin_checkov.py
- backend/engine/utils/plugin.py
- backend/utilities/plugin_runner/plugin.sh
Runs Checkov via the [Docker image](https://hub.docker.com/r/bridgecrew/checkov) instead of installed via pip/pipenv.
Additionally, cleaned up lint and typehint warnings, as well as improved the comments.
> [!NOTE]
> Checkov will be removed from the Pipfile as part of the next dependency update run.
Checkov has a very large and picky list of dependencies, which been a major source of dependency conflicts.  By using the Docker image instead, this allows us to keep other dependencies updated while updating Checkov regularly.
> Run Checkov via the Docker image

- backend/engine/plugins/checkov/main.py
- backend/engine/tests/test_plugin_checkov.py
Installs a signal handler to gracefully terminate the Checkov container.
Without this, when the plugin is terminated the Checkov container would continue running and then wouldn't be removed afterwards.
> [!NOTE]
> This currently only has an effect when running the Checkov plugin via the Plugin Runner utility.
> The engine currently sends a SIGKILL to the plugin when the timeout expires, which we can't trap.
Properly clean up the container when running via the Plugin Runner utility, and also prepare the plugin for when we add graceful shutdown to the engine.
Tested in non-prod environment as well as the Plugin Runner.
> Gracefully handle Checkov plugin shutdown

- backend/utilities/plugin_runner/toolbox/main.go
- backend/utilities/plugin_runner/toolbox/scan_pipe.go
Previously, output lines were assumed to fit within the default Scanner maximum buffer size of 64 KB.  This has quickly been determined to be overly optimistic!
Refactored the line scanning into scanPipe(), with a new maximum line buffer size of 128 MB.  If a line exceeds this threshold, then we display an error and forcefully close the pipe in order to avoid a deadlock.
Fixes deadlock when output (stdout or stderr) exceeds the default line buffer size.
Tested locally using the OWASP Dependency Check plugin, which writes a 270 KB result JSON.
> Plugin Runner Toolbox: Handle large output lines from the plugin

- backend/Pipfile
- backend/Pipfile.lock
This is a follow-up to: https://github.com/WarnerMedia/artemis/pull/376
Removes the cwe2 dependency as it is no longer used in any modules.
Reduce the size of our dependencies -- cwe2 was the second-largest non-dev dependency we were bringing in.
Tested locally.  Search for "cwe2" in the codebase no longer returns any results.
> Remove cwe2 dependency

- backend/.dockerignore
- backend/Dockerfiles/Dockerfile.engine
- backend/Makefile
When running `docker build`, removes the `--no-cache` and `--force-rm` options from always being set.
If needed, these can be set using the `DOCKER_BUILD_EXTRA_ARGS` var, e.g.:
```
make dist/docker/engine DOCKER_BUILD_EXTRA_ARGS='--no-cache --force-rm'
```
This will not affect CI deploys since we assume that each CI run will start with an empty cache anyway.
To inaugurate this change, Dockerfile.engine has been updated to use cache mounts for Apt, Pip, and Pipenv.
We want to make use of both layer caches and cache mounts when building our container images to improve the local dev cycle.  There may be additional tweaks needed to .dockerignore to avoid unnecessary rebuilds, but this is a first start.
Tested in non-prod environment as part of the 2024-12-09 "omnibus" deployment with Django …
> Re-enable default caching for docker build

- backend/Dockerfiles/Dockerfile.swift
- backend/Makefile
- backend/engine/plugins/swiftlint/settings.json
Switches the SwiftLint plugin to used the boxed runner.
This enables us to slim down the Swift container image by only including SwiftLint.  We now also verify the SHA-256 hash of the downloaded zip file.
Simplify SwiftLint plugin (no separate dependencies to maintain in Dockerfile.swift).
Tested in nonprod environment.
> Use boxed runner for SwiftLint

- backend/Dockerfiles/Dockerfile.boxed
- backend/Dockerfiles/Dockerfile.engine
- backend/Makefile
- backend/boxed-plugin.sh
- backend/docker-bake.hcl
Addresses two issues:
* Improves boxed plugin startup time.
* Lessens chance of free disk space errors, such as "Consider setting TMPDIR to a directory with more free space".
This is part of the longer-term effort to support distributions based on Musl libc (such as Alpine) by moving the glibc-based bundle into it's own directory. The bundle build process is now its own Dockerfile so we can re-use it (via docker-bake.hcl) to build both Glibc and Musl variants.
Extracting the plugin bundle into each container added to the startup time of each boxed plugin and required an additional 400+ MB of free space.
TODO
> Pre-extract the boxed plugin bundle

- backend/Dockerfiles/Dockerfile.boxed
- backend/Dockerfiles/Dockerfile.node14
- backend/engine/plugins/eslint/settings.json
- backend/engine/plugins/node_dependencies/settings.json
- backend/engine/plugins/nodejsscan/settings.json
Use the boxed runner for the eslint, node_dependencies, and nodejsscan plugins.
We also now include artemisdb and artemislib in the boxed plugin bundle.
Reduce dependencies to maintain in Dockerfile.node14.
Tested in nonprod.
> Use boxed runner for Node.js-related plugins

- backend/engine/processor/sbom_cdx.py
Our version of Trivy is currently facing a bug where it returns long passages of gibberish for their license information on their SBOM reports. Examples of this contain random metadata about the library or even the entire license agreement split into hundreds of licenses. This will just catch those instances and then log them. 
Trivy SBOM scans would error out when there were too many characters in a license
in a dev environment
> Bugfix trivy license

- backend/engine/plugins/README.md
- backend/utilities/plugin_runner/toolbox/lint.go
- backend/utilities/plugin_runner/toolbox/lint_test.go
- backend/utilities/plugin_runner/toolbox/schemas/configuration-finding.json
- backend/utilities/plugin_runner/toolbox/schemas/plugin-results.json
- backend/utilities/plugin_runner/toolbox/schemas/sbom-finding.json
- backend/utilities/plugin_runner/toolbox/schemas/secrets-finding.json
- backend/utilities/plugin_runner/toolbox/schemas/static-analysis-finding.json
- backend/utilities/plugin_runner/toolbox/schemas/unknown-finding.json
- backend/utilities/plugin_runner/toolbox/schemas/vulnerability-finding.json
Follow-up to: https://github.com/WarnerMedia/artemis/pull/394
Adds documentation and JSON schemas for SBOM, inventory, and configuration plugins.  These are based on the REST API spec and existing plugins.
Fill out missing documentation and add schema validation for the plugin types to the Plugin Runner.
Tested locally against plugins.
> Add schemas and docs for SBOM, inventory, and configuration plugins

- backend/utilities/plugin_runner/README.md
- backend/utilities/plugin_runner/plugin.sh
Checks if the engine/plugin container image exists and show a friendly reminder to build the image first.
Small improvement to UX (even I would get confused by the Docker error).
Only changes are to plugin runner utility.  Tested locally.
> Show friendlier error on missing container image

- backend/engine/utils/plugin.py
Stops the docker container when timeout is reached.
- Runs `docker stop <container-name>` when plugin timeout has been reached
- Previously, we just let `subprocess.run` kill the original `docker run ...` process, but the container would still run in the background. With this change, we tell the container to stop with SIGTERM, give it the default 10s grace period, then SIGKILL if it still hasn't exited.
- As a note, this currently doesn't do anything, as no active plugins specify a timeout in their `settings.json` and we do not set a default timeout.
- As a result, this change was tested by hardcoding the timeout to a small value.
- Containers currently continue running, orphaned, after the timeout has been reached. This fixes that.
- Tested in dev environment
> Engine - Gracefully shutdown containers when timeout is exceeded

- ui/terraform/environments/example/main.tf
- ui/terraform/modules/analyzer-ui/cloudfront.tf
- ui/terraform/modules/analyzer-ui/variables.tf
Allows optional CloudFront access logging to S3.
We don't automatically create the S3 bucket for logging since different setups likely have unique logging policies -- for example, some shops may have a single bucket to unify their access log collection with specific access controls.
Also: Fixes missing `response_headers_policy_id` in the example main.tf.
Supports enabling access logs.
Tested in nonprod environment.
> Support optional access logging

- backend/terraform/modules/analyzer/api_groups.tf
- backend/terraform/modules/analyzer/api_main.tf
- backend/terraform/modules/analyzer/api_sbom.tf
- backend/terraform/modules/analyzer/api_scans.tf
- backend/terraform/modules/analyzer/api_search.tf
- backend/terraform/modules/analyzer/api_system.tf
- orchestrator/terraform/modules/heimdall/api.tf
This associates a WAFv2 WebACL with the API Gateway stages in both the backend and orchestrator.  The WebACL is shipped with no rules by default; it is effectively a placeholder to allow rapid deployment of WAF rules in response to live incidents.
As part of this, we're also migrating from the deprecated `aws_api_gateway_deployment.stage_name` arg to `aws_api_gateway_stage`.
Provide a pre-associated WAFv2 WebACL for incident response.
Deployed to non-prod environment.
> Associate a WAFv2 WebACL with API Gateway stages

- backend/terraform/modules/analyzer/api_main.tf
- backend/terraform/modules/analyzer/variables.tf
- orchestrator/terraform/modules/heimdall/api.tf
- orchestrator/terraform/modules/heimdall/variables.tf
Enables [access logs for the API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html) stages for artemis-rest-api and heimdall-on-demand-api.
The log format is [CLF (Common Log Format)](https://httpd.apache.org/docs/current/logs.html#common) to make it easier out-of-the-box for log aggregators to parse the logs.
Note that additional account-wide manual configuration is required outside of Terraform to enable API Gateway to send logs to CloudWatch: [Permissions for CloudWatch logging](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html#set-up-access-logging-permissions)
Improve ability to debug and analyze REST API calls.
> Enable access logging for API Gateway stages

- backend/terraform/modules/analyzer/db.tf
- backend/terraform/modules/analyzer/variables.tf
Adds an option to enable [IAM authentication to the RDS cluster](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.html).
Enabling this option does not affect how Artemis connects to the database, it just enables an alternate method for admins to connect to the database.
This option may be required by organization security policy.
Deployed to non-prod environment.
> Add option to enable RDS IAM DB auth

- orchestrator/lambdas/layers/heimdall_utils/heimdall_utils/utils.py
- orchestrator/lambdas/tests/test_utils.py
- Timestamp format was `%Y-%m-%dT%H:%M:%SZ`
- This works fine with times in UTC (with a "Z" at the end), but doesn't parse non-UTC timezones
- Gitlab seems to not use UTC. This example was taken from their docs: `2024-06-28T03:44:20-07:00`
- This would fail with the previous timestamp format
Previously, this bug would cause issues retrieving timestamp information for Gitlab.
Tested in dev environment and by crafting strings
> Fix `is_valid_timestamp` for strings with timezone

- backend/lambdas/api/authorizer/authorizer/handlers.py
- backend/terraform/modules/analyzer/api_main.tf
- backend/terraform/modules/analyzer/api_provision.tf
- backend/terraform/modules/analyzer/api_system.tf
Moves all API Gateway endpoints to use the authorizer, including the ones previously using the `NONE` authorizer.
Additionally, the bulk of the type-checking issues have been corrected, but some remain (due to limitations with typechecking Django models).
Keeps all of the authorization logic in a single place.  This enables future flexibility in handling these requests, such as additional logging.
Additionally, this works around security scanners which flag any API Gateway resource with a `NONE` authorizer.
> Handle all API endpoints through the authorizer

- backend/terraform/modules/analyzer/api_main.tf
- backend/terraform/modules/analyzer/variables.tf
- orchestrator/terraform/modules/heimdall/api.tf
- orchestrator/terraform/modules/heimdall/variables.tf
Allows the API Gateway access log format to be customized.
The default remains the same (common log format).
Integration with security/monitoring tools may require a tool-specific custom log format (such as JSON).
Ran `terraform plan` and verified no changes to non-prod environment.
> Enable custom API log formats

- orchestrator/terraform/modules/scheduler/main.tf
`aws_cloudwatch_event_rule.is_enabled` has been deprecated in favor of `state`.  See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule#is_enabled-1
Clean up Terraform warning.
Ran `terraform plan` and confirmed no changes and no warnings.
> Clean up Terraform deprecation warning for aws_cloudwatch_event_rule

- backend/engine/plugins/trufflehog/main.py
- backend/engine/tests/test_plugin_trufflehog.py
Fixes how the Trufflehog plugin handles findings in commit messages
- Trufflehog can search commit messages (neat!)
- When Trufflehog finds a potential secret in commit messages, it doesn't provide anything for the `file` property.
- We weren't checking that the value in the `file` property is not `None`, so we'd error out there. This PR fixes that
Stability fix
Tests pass; working in dev environment
> Fix how Trufflehog plugin handles findings in commit messages

- ui/src/api/server.ts
- ui/src/locale/en/messages.po
- ui/src/pages/ResultsPage.tsx
Hides the line number in secret findings when it is not set
- Missed in https://github.com/WarnerMedia/artemis/pull/440
- Previously the surrounding text was still printed out if line is not provided. This would result in the text being `Commit Message (Line )`. This removes the ` (Line )` bit, and it will now just be `Commit Message`.
- Having an empty line didn't make sense
> Hide line number in secrets details when line number is not set

- backend/terraform/modules/analyzer/messaging.tf
- backend/terraform/modules/analyzer/variables.tf
- orchestrator/terraform/modules/heimdall/lambdas.tf
This PR Updates the terraform configurations to ignore updates to: 
- The `schedule_expression` in the `heimdall-repo-scan-loop-rate` cloudwatch rule
- The `state` for the `artemis-run-every-minute` cloudwatch rule
This PR will allow users to update these configurations without them being overwritten by new terraform updates. 
ran `terraform plan` locally
> Update Terraform configurations to ignore certain fields

- backend/engine/plugins/lib/findsecbugs_common/parsing_util.py
Improves the parsing of findsecbugs results
- The Findsecbugs plugins would fail if results had anything other than exactly two colons (`:`) or was lacking a filename. This handles those cases
- The one case that isn't handled is if there are no colons in the line. I could not get this to trigger in my testing, so it would be unclear how we should parse the line in that case. Instead, we raise a specific exception so that we can easily debug.
Findsecbugs was crashing frequently and this handles those cases more gracefully.
> Improve parsing of findsecbugs results

- backend/Dockerfiles/Dockerfile.engine
Install the Docker buildx (aka [BuildKit](https://docs.docker.com/build/buildkit/)) plugin in the engine container. Docker will use BuildKit as the default builder when the engine attempts to build container images during a scan.
This fixes the Docker warning in the engine logs:
> DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
> Fix Docker deprecation warning when building images

- backend/lambdas/api/users_keys/users_keys/util/parsers.py
- backend/lambdas/api/users_services/users_services/util/parsers.py
Handles `JSONDecodeError`s in the users lambdas
- `users_keys` and `users_services` would occasionally raise a `JSONDecodeError` with message `Expecting value: line 1 column 1 (char 0)`. We can reproduce this error message outside of Artemis with `python -c "import json; json.loads('')"`, implying the problem is when the body is empty string.
- The existing `or "{}"` should cover this case, as empty string is falsey. So, something else is going. That said, any `JSONDecodeError` should be treated as validation failing, so we handle that case generically by raising `ValidationError` instead of handling this particular error.
- These lambdas were occasionally crashing with errors. This PR handles the underlying error that caused these crashes.
> Handle exception in users lambdas

- .github/workflows/test_backend.yml
- .github/workflows/test_orchestrator.yml
- .github/workflows/test_ui.yml
Explicitly sets the `permissions` block for each GitHub Actions job.
Resolves CodeQL "Workflow does not contain permissions" findings.
Tested workflows via this PR.
> Explicitly set permissions for jobs

- backend/lambdas/api/repo/repo/post.py
- backend/lambdas/api/repo/repo/services/ado.py
Azure DevOps was not obeying the `nat_connect` field in a `services.json` entry
- Azure DevOps just didn't obey the `nat_connect` field. This PR makes it do that
- We have `nat_connect` fields, so let's use them
- Tests pass
> Modify ADO to obey `nat_connect` from `services.json`

- backend/lambdas/api/system_services/system_services/util/service.py
- backend/lambdas/api/system_services/tests/test_service.py
Addition to https://github.com/WarnerMedia/artemis/pull/485 to fix ADO entries in the `system/services` endpoint
- ADO services in the `system/services` endpoint were failing to authenticate successfully due to the API Key format change in https://github.com/WarnerMedia/artemis/pull/485
- This modifies the `_test_ado` function to base64 encode the API Key before use
- ADO services were not reporting as being able to authenticate (despite being able to authenticate and pull things down just fine) due to the change in secret format.
Tests pass and working in dev environment
> Fix ADO in system/services endpoint

- .editorconfig
- ui/.prettierignore
- ui/config/env.js
- ui/config/getHttpsConfig.js
- ui/config/jest/babelTransform.js
- ui/config/jest/cssTransform.js
- ui/config/jest/fileTransform.mjs
- ui/config/modules.js
- ui/config/paths.js
- ui/config/webpack.config.js
- ui/config/webpack/persistentCache/createEnvironmentHash.js
- ui/config/webpackDevServer.config.js
- ui/package.json
- ui/scripts/build.js
- ui/scripts/start.js
- ui/scripts/test.js
Cleans up the Create-React-App ejected files to match our Prettier config.
* Moved the list of files to include from `package.json` to `.prettierignore` so it's in a single place and can include comments.
* Added CRA config files and build scripts to Prettier.
* Also added `/*.js` and `/*.mjs` to cover upcoming ESLint updates.
* Updated the `.editorconfig` for `*.mjs` files to match `*.js` files.
Use consistent formatting between our source and config files.
Only affects formatting; tested via CI in this PR.
> Reformat ejected CRA scripts with Prettier

- backend/pyproject.toml
- orchestrator/pyproject.toml
Adds a minimal `project` section to the backend and heimdall `pyproject.toml` files.
The version `2.7.0` is the somewhat-arbitrary version we've already been referencing in the UI, so this just makes it official.
Also fixes a missed update to Python 3.12 in the Heimdall `pyproject.toml`.
When testing the migration from Pipenv to uv, the `project` metadata is needed to define the dependencies shared between projects.  If not defined, then the migration script will insert invalid values, so we need to manually set them ahead of time.
Validated using [validate-pyproject](https://pypi.org/project/validate-pyproject/).
> Add project section to pyproject.toml

- backend/pytest.ini
Explicitly ignores the `utcnow()` deprecation warning in botocore from unit tests.
We can't do anything about this warning until boto3/botocore finds a backwards-compatible solution: https://github.com/boto/boto3/issues/3889
Clean up remaining unit test warnings.
Ran backend unit tests and confirmed no warnings.
> Ignore utcnow DeprecationWarning from botocore

- backend/utilities/plugin_runner/toolbox/go.mod
- backend/utilities/plugin_runner/toolbox/main.go
Fixes a potential format string injection in the Plugin Runner Toolbox usage message.  This shouldn't be exploitable since we control the invocation via the entrypoint script generated by `plugin.sh`.
Also builds with [Go 1.24.6](https://go.dev/doc/devel/release#go1.24.6). This release includes a fix for `os/exec`.  We haven't run into any issues, but this is to be on the safe side.
Clean up lint warning and preventative maintenance.
Tested running plugin runner locally.
> Plugin Runner Toolbox: Fix format string injection and build with Go 1.24.6
